# Ticket https://www.bitergia.net/redmine/issues/2029
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AbuseFilter.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ActiveAbstract.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AntiBot.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AntiSpoof.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ApiSandbox.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ArticleFeedback.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ArticleFeedbackv5.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AssertEdit.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Babel.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CategoryTree.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CentralAuth.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CentralNotice.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CharInsert.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CheckUser.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Cite.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/cldr.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ClickTracking.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ClientSide.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CodeEditor.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CodeReview.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Collection.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CommunityHiring.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CommunityVoice.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ConfirmEdit.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Contest.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ContributionReporting.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ContributionTracking.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CustomData.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CustomUserSignup.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/DisableAccount.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/DismissableSiteNotice.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/DonationInterface.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/DoubleWiki.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/DynamicPageList.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/E3Experiments.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Echo.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/EditPageTracking.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/EducationProgram.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/EmailCapture.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ExpandTemplates.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ExtensionDistributor.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/FeaturedFeeds.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/FlaggedRevs.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/FormPreloadPostCache.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Gadgets.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/GlobalBlocking.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/GlobalUsage.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/GoogleNewsSitemap.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ImageMap.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/InputBox.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Insider.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/intersection.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Interwiki.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/LabeledSectionTransclusion.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/LandingCheck.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/LastModified.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/LiquidThreads.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/LocalisationUpdate.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MapSources.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MarkAsHelpful.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Math.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MobileFrontend.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MoodBar.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MWSearch.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Narayam.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/NewUserMessage.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Nuke.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/OAI.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/OggHandler.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/OpenSearchXml.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Oversight.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/PagedTiffHandler.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/PageTriage.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ParserFunctions.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Parsoid.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/PdfHandler.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Poem.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/PoolCounter.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/PostEdit.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ProofreadPage.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Quiz.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/RandomRootPage.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ReaderFeedback.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/RelatedArticles.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/RelatedSites.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Renameuser.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/RSS.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ScanSet.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Scribunto.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SecurePoll.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ShortUrl.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SimpleAntiSpam.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SiteMatrix.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SkinPerPage.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SpamBlacklist.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/StringFunctionsEscaped.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SubPageList3.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SubpageSortkey.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SwiftCloudFiles.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SyntaxHighlight_GeSHi.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TimedMediaHandler.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/timeline.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TitleBlacklist.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TitleKey.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TorBlock.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Translate.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TranslationNotifications.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TrustedXFF.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/UnicodeConverter.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/UploadBlacklist.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/UploadWizard.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/UserDailyContribs.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/UserThrottle.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Vector.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/VipsScaler.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/VisualEditor.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WebFonts.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Wikibase.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikiEditor.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/wikihiero.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikiLove.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikimediaIncubator.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikimediaMessages.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikimediaShopLink.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ZeroRatedMobileAccess.git
git clone https://gerrit.wikimedia.org/r/p/mediawiki/php/wikidiff2.git
