## Copyright (C) 2012 Bitergia
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
##
## This file is a part of the vizGrimoire.R package
##
## vizgrimoire.R
##
## R library for the vizgrimoire system
##
## Authors:
##   Jesus M. Gonzalez-Barahona <jgb@bitergia.com>
##

##
## Get arguments from the command line
##
##  - dbschema: MySQL database schema to use, generated by CVSAnalY2
##  - user: MySQL user with permissions to access the schema
##  - passwd: password corresponding to user
##  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
##      (in fact, first day after the period)
##  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
##
##
ConfFromCommandLine <- function () {
  ## Get command line args, and produce variables for the script
  args <- commandArgs(trailingOnly = TRUE)

  if (length(args) > 3) {
    enddate <- args[4]
  } else {
    enddate <- "2100-01-01"
  }
  enddatesplit <- strsplit(enddate,'-')
  endyear <- enddatesplit[[1]][1]
  endmonth <- enddatesplit[[1]][2]
  enddate <- paste (c("'", enddate, "'"), collapse='')
  
  if (length(args) > 4) {
    startdate <- args[5]
  } else {
    startdate <- "1900-01-01"
  }
  startdatesplit <- strsplit(startdate,'-')
  startyear <- startdatesplit[[1]][1]
  startmonth <- startdatesplit[[1]][2]
  startdate <- paste (c("'", startdate, "'"), collapse='')

  conf <- list (database = args[1],
                user = args[2],
                password = args[3],
                startdate = startdate,
                enddate = enddate)
  return (conf)
}

##
## Penalize scientific notation by 10 chars
##
options(scipen=10)

##
## Database-related classes & functions
##

library(RMySQL)
##
## Connect to the database and prepare...
##

SetDBChannel <- function (user, password, database, host="localhost") {
  mychannel <<- dbConnect(MySQL(), user=user, password=password,
                          db=database, host="localhost")
}

##
## Find out kind of repository (bugzilla, launchad, etc.) and
##  store it in common configuration list
##
FindoutRepoKind <- function () {
  q <- new ("Query", sql = "SELECT name FROM supported_trackers")
  kind <- run(q)$name[1]
  return (kind)
}

# To install RColorBrewer
# $sudo R
# > install.packages('RColorBrewer', dep = T)
# Note use display.brewer.pal(...) to check colors
# example: display.brewer.pal(9, "Greens")
library(RColorBrewer)

blues = brewer.pal(5,'Blues')
reds = brewer.pal(5,'Reds')
greens = brewer.pal(5,'Greens')

#
# List of colors for plots
#
colors <- c("black", "green", "red", "blue", "orange", "brown")


# Complete a weekly dataframe with zero for missing weeks
#
# Gets as input a dataframe with weekly data. It hast to
# include a "yearweek" column, which is an integer year*52+week
# Produces a dataframe with zero rows for missing weeks
#
completeZeroWeekly <- function (data) {

  firstweek = as.integer(data$yearweek[1])
  lastweek = as.integer(data$yearweek[nrow(data)])
  weeks = data.frame('yearweek'=c(firstweek:lastweek))
  completedata <- merge (data, weeks, all=TRUE)
  completedata[is.na(completedata)] <- 0
  return (completedata)
}

# Merge two dataframes with weekly data, filling holes with 0
#
# Both dataframes should have a "yearweek" column,
# which is an integer year*52+week
#
mergeWeekly <- function (d1, d2) {

  d = completeZeroWeekly (merge (d1, d2, all=TRUE))

  return (d)
}

# Complete a monthly dataframe with zero for missing months
#
# Gets as input a dataframe with montly data. It hast to
# include a "id" column, which is an integer year*12+month
# Produces a dataframe with zero rows for missing months
#
completeZeroMonthly <- function (data) {

  firstmonth = as.integer(data$id[1])
  lastmonth = as.integer(data$id[nrow(data)])
  months = data.frame('id'=c(firstmonth:lastmonth))
  completedata <- merge (data, months, all=TRUE)
  completedata[is.na(completedata)] <- 0
  return (completedata)
}

# Merge two dataframes with monthly data, filling holes with 0
#
# Both dataframes should have a "id" column,
# which is an integer year*12+week
#
mergeMonthly <- function (d1, d2) {

  d = completeZeroMonthly (merge (d1, d2, all=TRUE))

  return (d)
}

##
## toTextDate: convert two vectors with integers for year, month into
##  a vector with text
##
## Example: 2012, 2 -> Feb 2012
##
toTextDate <- function (year, month) {
  abb.months <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
  text <- paste (abb.months[month], as.character(year))
  return (text)
}


#
# Plot several columns of a timeserie
#
#  data: data frame to plot
#  columns: names of the columns in data frame to plot
#  labels: strings to show as labels
#

plotTimeSerieWeekN <- function (data, columns, filename, labels=columns) {

  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
  pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')
  
  # Build label for Y axis
  label <- ""
  for (col in 1:length(columns)) {
    if (col != 1) {
      label <- paste (c(label, " / "), collapse='')
    }
    label = paste (c(label, labels[col], " (", colors[col] ,")"),
      collapse='')
  }
  
  # Regular plot
  pdf(file=pdffilename, height=3.5, width=5)
  timeserie <- ts (data[columns[1]],
                   start=c(data$year[1],data$week[1]), frequency=52)
  ts.plot (timeserie, col=colors[1], ylab=label)
  if (length (columns) > 1) {
    for (col in 2:length(columns)) {
      timeserie <- ts (data[columns[col]],
                       start=c(data$year[1],data$week[1]), frequency=52)
      lines (timeserie, col=colors[col])
    }
  }
  dev.off()

# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
}

#
# Plot several columns of a timeserie
#
#  data: data frame to plot
#  columns: names of the columns in data frame to plot
#  labels: strings to show as labels
#

plotTimeSerieMonthN <- function (data, columns, filename, labels=columns) {

  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
  pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')
  
  # Build label for Y axis
  label <- ""
  for (col in 1:length(columns)) {
    if (col != 1) {
      label <- paste (c(label, " / "), collapse='')
    }
    label = paste (c(label, labels[col], " (", colors[col] ,")"),
      collapse='')
  }
  
  # Regular plot
  pdf(file=pdffilename, height=3.5, width=5)
  timeserie <- ts (data[columns[1]],
                   start=c(data$year[1],data$month[1]), frequency=12)
  ts.plot (timeserie, col=colors[1], ylab=label)
  if (length (columns) > 1) {
    for (col in 2:length(columns)) {
      timeserie <- ts (data[columns[col]],
                       start=c(data$year[1],data$month[1]), frequency=12)
      lines (timeserie, col=colors[col])
    }
  }
  dev.off()

# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
}

plotTimeSerieYearN <- function (data, columns, filename, labels=columns) {

  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdffilenamelog <- paste (c(filename, "-log.pdf"), collapse='')
  pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
  pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')

  # Build label for Y axis
  label <- ""
  for (col in 1:length(columns)) {
    if (col != 1) {
      label <- paste (c(label, " / "), collapse='')
    }
    label = paste (c(label, labels[col], " (", colors[col] ,")"),
      collapse='')
  }
  
  timeserie <- ts (data[columns], start=data$year[1])
  ## Regular plot
  pdf(file=pdffilename, height=3.5, width=5)
  ts.plot (timeserie, gpars=list(col=colors, ylab=label))
  dev.off()
  ## Log10 plot
  pdf(file=pdffilenamelog, height=3.5, width=5)
  ts.plot (log10(timeserie), gpars=list(col=colors, ylab=label))
  dev.off()
  
  
# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
}


#
# Plot histogram and density of probability for data frame (single column)
#
plotHistogramTime <- function (data, filename, label, title='') {

  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdf(pdffilename, height=5, width=5)
#  hist(data, prob= T, breaks='FD', col=blues[3], xlab = label, main = title)
  hist(data, freq=TRUE, breaks=15, col="orange", xlab = label, main = title)
#  lines(density(data), col=reds[3], lwd = 2)
  dev.off()
}
#library(vioplot)

#
# Plot boxplot for data frame
#
plotBoxPlot <- function (data, filename, label = '', title = '') {
  
  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdf(pdffilename, height=10, width=2)
  boxplot(data, col = greens[2], main = title, ylab = "days", xlab = label)
  # Mark top 3 outliers
  #top3 = rev(sort(data))[1:3]
  #print(top3)
  #text(rep(1,3), y = top3, label = paste(top3, 'days'), pos = 4)
  dev.off()
}

#
# Plot distribution of times
#
# Plots several charts:
#  - Histogram and density of probability for all tickets
#  - Histogram and density of probability for quickly closed tickets
#  - Histogram and density of probability for slowly closed tickets
# Threshold is for splitting in quick/slow (in days)
#
plotTimeDist <- function (data, filename, unit = 'days', threshold = 30,
                          variable = 'Time') {

  label <- paste (c(variable, ' (', unit, ')'), collapse='')
  # All tickets
  plotHistogramTime (data, filename, label)
  plotBoxPlot (data, paste (c (filename, '-boxplot'), collapse=''))
  # Quickly closed tickets
  quickly <- data[data <= threshold]
  if (length(quickly) > 0) {
    plotHistogramTime (quickly, paste (c (filename, '-quick'), collapse=''),
                       label)
    plotBoxPlot (quickly, paste (c (filename, '-quick-boxplot'), collapse=''))
  }
  # Slowly closed tickets
  slowly <- data[data > threshold]
  if (length(slowly) > 0) {
    plotHistogramTime (slowly, paste (c (filename, '-slow'), collapse=''),
                       label)
    plotBoxPlot (slowly, paste (c (filename, '-slow-boxplot'), collapse=''))
  }
#  pdf(paste (c (filename, '-vioplot.pdf'), collapse=''), height=10, width=4)
#  vioplot(data, quickly, slowly, col='gold', varwidth=TRUE)
#  dev.off()
}

## #
## # Plot time distributions and boxplots for time to fix in all years
## #
## plotTimeDistYear <- function (data, filename) {
##   for (year in data$year_open[1] : data$year_open[nrow(data)]) {
##     filename = paste(c(filename, '-',year), collapse='')
##     yearData <- data[data$year_open == year,]
##     plotTimeDist (yearData$ttofixm, filename, 'minutes',
##                   variable = 'Time to fix, first close')
##   }
## }

library(rjson)
#
# Create a JSON file with some R object
#
createJSON <- function (data, filename) {
  sink(filename)
  cat(toJSON(data))
  sink()
}

##
## GetYear
##
## Get the year of a datetime object
##
## Year as four digits (eg: 2012)
##
GetYear <- function (time) {
  return (1900 + as.POSIXlt(time)$year)
}

##
## GetMonth
##
## Get the month of a datetime object
##
## Month as an integer 0:11 (eg: Jan is 0)
##
GetMonth <- function (time) {
  return (as.POSIXlt(time)$mon)
}
