#
# Usage:
#  R --no-restore --no-save --args dbschema user passwd [enddate [startdate] ] < its-analysis.R > script.out

# Get arguments from the command line
#
#  - dbschema: MySQL database schema to use, generated by CVSAnalY2
#  - user: MySQL user with permissions to access the schema
#  - passwd: password corresponding to user
#  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
#      (in fact, first day after the period)
#  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
#
# Note: this script works with bicho databases obtained from Bugzilla

# Times class
source("../../ClassTimes.R")
# TimeSeriesYears class
source("../../ClassTimeSeriesYears.R")
# Query class
source("../../ClassQuery.R")
# QueryTimeSerie class
source("../../ClassQueryTimeSerie.R")
# ITSTicketsTimes class
source("../../ClassITSTicketsTimes.R")
# ITSMonthly class
source("../../ClassITSMonthly.R")
# ITSMonthlyOpen class
source("../../ClassITSMonthlyOpen.R")
# ITSMonthlyChanged class
source("../../ClassITSMonthlyChanged.R")
# ITSMonthlyClosed class
source("../../ClassITSMonthlyClosed.R")

source("../../vizgrimoire.R")

# Get command line args, and produce variables for the script
args <- commandArgs(trailingOnly = TRUE)

database <- args[1]
user <- args[2]
password <- args[3]

if (length(args) > 3) {
  enddate <- args[4]
} else {
  enddate <- "2100-01-01"
}
enddatesplit <- strsplit(enddate,'-')
endyear <- enddatesplit[[1]][1]
endmonth <- enddatesplit[[1]][2]
enddate <- paste (c("'", enddate, "'"), collapse='')

if (length(args) > 4) {
   startdate <- args[5]
} else {
   startdate <- "1900-01-01"
}
startdatesplit <- strsplit(startdate,'-')
startyear <- startdatesplit[[1]][1]
startmonth <- startdatesplit[[1]][2]
startdate <- paste (c("'", startdate, "'"), collapse='')

SetDBChannel (user, password, database)

##
## Time to close and related times
##

## Closed tickets: time ticket was open, first closed, time-to-first-close
issues_closed <- new ("ITSTicketsTimes")
JSON(issues_closed, 'its-issues_closed.json')

## Distribution of time to fix (first close)
tofix <- new ("Times", issues_closed$ttofix, "days",
              "Time to fix, first close")
PlotDist (tofix, 'its-distrib_time_to_fix')
              
## Distribution of time to fix (last close)
tofix.last <- new ("Times", issues_closed$ttofixlast, "days",
              "Time to fix, last close")
PlotDist (tofix.last, 'its-distrib_time_to_fix_last')

## Distribution of time to fix (first close, hours)
tofix.hours <- new ("Times", issues_closed$ttofixh, "hours",
                    "Time to fix, first close")
PlotDist (tofix.hours, 'its-distrib_time_to_fix_hours')

## Distribution of time to fix (first close, minutes)
tofix.minutes <- new ("Times", issues_closed$ttofixm, "minutes",
                      "Time to fix, first close")
PlotDist (tofix.minutes, 'its-distrib_time_to_fix_min')

## Which quantiles we're interested in
##quantiles_spec = c(1,.99,.95,.9,.75,.5,.25,.1,0)
quantiles_spec = c(.99,.95,.5,.25)

## Yearly quantiles of time to fix (minutes)
#quantiles_ttofixm_year <- toQuantilesYear (issues_closed, quantiles_spec)
quantiles <- QuantilizeYears (issues_closed, quantiles_spec)

#quantiles <- new ("TimeSeriesYears", quantiles_ttofixm_year, c(.99,.95))
Plot(quantiles, 'its-quantiles-year-time_to_fix_min')
JSON(quantiles, 'its-quantiles-year-time_to_fix_min.json')

# Yearly distributions of time to fix (minutes)
plotTimeDistYear(issues_closed, 'its-distrib_time_to_fix_min')


## # Time-to-attention (from open to first change or first comment)
## q <- "SELECT issue_id, issue,
##      	issues.submitted_on as time_open,
##         MIN(ch.time_first) AS time_attention,
## 	TIMESTAMPDIFF (DAY, submitted_on, MIN(ch.time_first)) AS tattention,
## 	TIMESTAMPDIFF (HOUR, submitted_on, MIN(ch.time_first)) AS tattentionh,
## 	TIMESTAMPDIFF (MINUTE, submitted_on, MIN(ch.time_first)) AS tattentionm
##       FROM issues, (
##          SELECT
##            issue_id,
##            MIN(changed_on) AS time_first
##          FROM changes
##          GROUP BY issue_id
##         UNION
##          SELECT
##            issue_id,
##            MIN(submitted_on) AS time_first
##          FROM comments
##          GROUP BY issue_id
##          ) ch
##       WHERE issues.id = ch.issue_id
##       GROUP BY issue_id
##       ORDER BY issue_id"
## issues_attended <- query (q)

## time_to_attention <- issues_attended$tattention
## time_to_attention_hours <- issues_attended$tattentionh
## time_to_attention_minutes <- issues_attended$tattentionm

## # Distribution of time to attention
## plotTimeDist (time_to_attention, 'its-distrib_time_to_attention',
##               variable = 'Time to attention')
## plotTimeDist (time_to_attention_hours,
##               'its-distrib_time_to_attention_hours', 'hours',
##               variable = 'Time to attention')
## plotTimeDist (time_to_attention_minutes,
##               'its-distrib_time_to_attention_min', 'minutes',
##               variable = 'Time to attention')


## #
## # Open, closed issues per week
## #

## # New tickets per week
## q <- "SELECT YEAR (submitted_on) * 52 + WEEK (submitted_on) AS yearweek,
##         DATE_FORMAT(submitted_on, '%Y %V') AS year_week,
## 	YEAR (submitted_on) AS year,
##         WEEK (submitted_on) AS week,
##         COUNT(*) AS open
##       FROM issues
##       GROUP BY yearweek"
## issues_open_weekly <- query(q)

## # Changed tickets per week
## q <- "SELECT year(changed_on) * 52 + WEEK (changed_on) AS yearweek,
##         DATE_FORMAT(changed_on, '%Y %V') AS year_week,
## 	YEAR (changed_on) AS year,
##         WEEK (changed_on) AS week,
##         count(changed_by) AS changed,
##         count(distinct(changed_by)) AS changers
##       FROM changes
##       GROUP BY yearweek"
## issues_changed_weekly <- query(q)

## # Closed tickets per week (using first closing date)
## q <- "SELECT YEAR (time_closed) * 52 + WEEK (time_closed) AS yearweek,
##         DATE_FORMAT(time_closed, '%Y %V') AS year_week,
## 	YEAR (time_closed) AS year,
##         WEEK (time_closed) AS week,
##         COUNT(*) as closed
##       FROM (
##          SELECT issue_id, MIN(changed_on) time_closed
##          FROM changes 
##          WHERE new_value='RESOLVED' OR new_value='CLOSED' 
##          GROUP BY issue_id) ch 
##       GROUP BY yearweek"
## issues_closed_weekly <- query(q)

## # Closed tickets per week (using last closing date)
## q <- "SELECT YEAR (time_closed) * 52 + WEEK (time_closed) AS yearweek,
##         DATE_FORMAT(time_closed, '%Y %V') AS year_week,
## 	YEAR (time_closed) AS year,
##         WEEK (time_closed) AS week,
##         COUNT(*) as closed_last
##       FROM (
##          SELECT issue_id, MAX(changed_on) time_closed
##          FROM changes 
##          WHERE new_value='RESOLVED' OR new_value='CLOSED' 
##          GROUP BY issue_id) ch 
##       GROUP BY yearweek"
## issues_closed_weekly_last <- query(q)

## # Tickets open and closed (first close) per week
## issues_open_closed_week <- mergeWeekly (issues_open_weekly, issues_closed_weekly)
## plotTimeSerieWeekN (issues_open_closed_week, c("open", "closed"),
##                     "its-open-closed-week", c("Tickets open", "closed"))

## # Tickets open and closed (last close) per week
## issues_open_closed_last_week <- mergeWeekly (issues_open_weekly,
## 			     		     issues_closed_weekly_last)
## plotTimeSerieWeekN (issues_open_closed_last_week, c("open", "closed_last"),
##                     "its-open-closed-last-week", c("Tickets open", "closed"))

## # Tickets closed (first and last close) per week
## issues_closed_week <- mergeWeekly (issues_closed_weekly,
## 			     		     issues_closed_weekly_last)
## plotTimeSerieWeekN (issues_closed_week, c("closed", "closed_last"),
##                     "its-closed-week",
## 		    c("Tickets closed first", "last"))

## # Tickets changed per week
## issues_changed_closed_week <- mergeWeekly (issues_changed_weekly,
##                                            issues_closed_weekly)
## plotTimeSerieMonthN (issues_changed_closed_week, c("changed", "closed"),
##                      "its-changed-week",
##                      c("Tickets changed", "closed"))

#
# Open, closed, changed issues per month
#

open.monthly <- new ("ITSMonthlyOpen")
JSON(open.monthly, "its-open-monthly.json")

changed.monthly <- new ("ITSMonthlyChanged")
JSON(changed.monthly, "its-changed-monthly.json")

# Closed tickets per month (using first closing date)
## q <- "SELECT year(time_closed) * 12 + month(time_closed) AS id,
##         year(time_closed) AS year,
##         month(time_closed) AS month,
##         DATE_FORMAT (time_closed, '%b %Y') as date,
##         COUNT(*) as closed
##       FROM (
##          SELECT issue_id, MIN(changed_on) time_closed
##          FROM changes 
##          WHERE new_value='RESOLVED' OR new_value='CLOSED' 
##          GROUP BY issue_id) ch 
##       GROUP BY year,month"
## issues_closed_monthly <- query(q)

closed.monthly <- new ("ITSMonthlyClosed")
JSON(closed.monthly, "its-closed-monthly.json")

print Error

# Closed tickets per month (using last closing date)
q <- "SELECT year(time_closed) * 12 + month(time_closed) AS id,
        year(time_closed) AS year,
        month(time_closed) AS month,
        DATE_FORMAT (time_closed, '%b %Y') as date,
        COUNT(*) as closed_last
      FROM (
         SELECT issue_id, MAX(changed_on) time_closed
         FROM changes 
         WHERE new_value='RESOLVED' OR new_value='CLOSED' 
         GROUP BY issue_id) ch 
      GROUP BY year,month"
issues_closed_monthly_last <- query(q)

# Tickets open and closed (first close) per month
issues_open_closed_month <- mergeMonthly (issues_open_monthly,
                                          issues_closed_monthly)
plotTimeSerieMonthN (issues_open_closed_month, c("open", "closed"),
                     "its-open-closed-month", c("Tickets open", "closed"))

# Tickets open and closed (last close) per month
issues_open_closed_last_month <- mergeMonthly (issues_open_monthly,
                                               issues_closed_monthly_last)
plotTimeSerieMonthN (issues_open_closed_last_month, c("open", "closed_last"),
                     "its-open-closed-last-month", c("Tickets open", "closed"))

# Tickets closed (first and last close) per month
issues_closed_month <- mergeMonthly (issues_closed_monthly,
                                     issues_closed_monthly_last)
plotTimeSerieMonthN (issues_closed_month, c("closed", "closed_last"),
                     "its-closed-month",
                     c("Tickets closed first", "last"))

# Tickets changed per month
issues_changed_closed_month <- mergeMonthly (issues_changed_monthly,
                                             issues_closed_monthly)
plotTimeSerieMonthN (issues_changed_closed_month, c("changed", "closed"),
                     "its-changed-month",
                     c("Tickets changed", "closed"))

issues_monthly <- mergeMonthly (issues_changed_closed_month,
                                issues_open_monthly)
createJSON (issues_monthly, "its-timeserie.json")

#
# Number of changes, comments per issue
#
q <- "SELECT ch.issue_id AS issue_id,
        changes,
        comments 
      FROM
        (SELECT issue_id,
           COUNT(*) AS changes 
         FROM changes 
         GROUP BY issue_id) ch, 
        (SELECT issue_id,
           COUNT(*) as comments 
         FROM comments 
         GROUP BY issue_id) com 
      WHERE ch.issue_id = com.issue_id 
      ORDER BY comments DESC"
issues_operations <- query (q)

plotBoxPlot (issues_operations$changes, 'its_issue_changes-bloxplot')
plotBoxPlot (issues_operations$comments, 'its_issue_comments-bloxplot')
plotBoxPlot (issues_operations$changes + issues_operations$comments,
             'its_issue_operations-bloxplot')
