## Copyright (C) 2012, 2013 Bitergia
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
##
## This file is a part of the vizGrimoire R package
##  (an R library for the MetricsGrimoire and vizGrimoire systems)
##
## Auxiliary.R
##
## Auxiliary code for the classes in the package
##
## Authors:
##   Jesus M. Gonzalez-Barahona <jgb@bitergia.com>
##
## Note: this file should be (alphabetically) the first one in the list
##  of files with R source code for the package. It ssems that files are
##  run in alphabetic order, and this one includes facilties needed by
##  the rest. An laternative would be to use a "Collate" field in the
##  DESCRIPTION file.
##

## Get arguments from the command line
##
##  - dbschema: MySQL database schema to use, generated by CVSAnalY2
##  - user: MySQL user with permissions to access the schema
##  - passwd: password corresponding to user
##  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
##      (in fact, first day after the period)
##  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
##
##
ConfFromCommandLine <- function () {
  ## Get command line args, and produce variables for the script
  args <- commandArgs(trailingOnly = TRUE)

  if (length(args) > 3) {
    enddate <- args[4]
  } else {
    enddate <- "2100-01-01"
  }
  enddatesplit <- strsplit(enddate,'-')
  endyear <- enddatesplit[[1]][1]
  endmonth <- enddatesplit[[1]][2]
  enddate <- paste (c("'", enddate, "'"), collapse='')
  
  if (length(args) > 4) {
    startdate <- args[5]
  } else {
    startdate <- "1900-01-01"
  }
  startdatesplit <- strsplit(startdate,'-')
  startyear <- startdatesplit[[1]][1]
  startmonth <- startdatesplit[[1]][2]
  startdate <- paste (c("'", startdate, "'"), collapse='')

  conf <- list (database = args[1],
                user = args[2],
                password = args[3],
                startdate = startdate,
                enddate = enddate)
  return (conf)
}

## Get arguments from parameters to this function
##
##  - dbschema: MySQL database schema to use, generated by CVSAnalY2
##  - user: MySQL user with permissions to access the schema
##  - passwd: password corresponding to user
##  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
##      (in fact, first day after the period)
##  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
##
##
ConfFromParameters <- function (dbschema, user = NULL, password = NULL,
                                host = "127.0.0.1", port = 3306,
                                group = NULL,
                                enddate = NULL, startdate = NULL) {
  if (is.null(enddate)) {
    enddate <- "2100-01-01"
  }
  enddate <- paste (c("'", enddate, "'"), collapse='')
  if (is.null(startdate)) {
    startdate <- "1900-01-01"
  }
  startdate <- paste (c("'", startdate, "'"), collapse='')

  conf <- list (database = dbschema,
                user = user,
                password = password,
                host = host,
                port = port,
                group = group,
                startdate = startdate,
                enddate = enddate)
  return (conf)
}

##
## Penalize scientific notation by 10 chars
##
options(scipen=10)

##
## Database-related classes & functions
##

library(RMySQL)
##
## Connect to the database and prepare...
##

SetDBChannel <- function (user=NULL, password=NULL, database,
                          host="127.0.0.1", port=3306,
                          group=NULL) {
  if (is.null(group)) {
    mychannel <<- dbConnect(MySQL(), user=user, password=password,
                            db=database, host=host, port=port)
  } else {
    mychannel <<- dbConnect(MySQL(), group=group,
                            db=database)
  }    
  dbGetQuery(mychannel, "SET NAMES 'utf8'")
}

##
## Find out kind of repository (bugzilla, launchad, etc.) and
##  store it in common configuration list
##
FindoutRepoKind <- function () {
  q <- new ("Query", sql = "SELECT name FROM supported_trackers")
  kind <- run(q)$name[1]
  return (kind)
}

# Note use display.brewer.pal(...) to check colors
# example: display.brewer.pal(9, "Greens")
library(RColorBrewer)

blues = brewer.pal(5,'Blues')
reds = brewer.pal(5,'Reds')
greens = brewer.pal(5,'Greens')

#
# List of colors for plots
#
colors <- c("black", "green", "red", "blue", "orange", "brown")


# Complete a weekly dataframe with zero for missing weeks
#
# Gets as input a dataframe with weekly data. It hast to
# include a "yearweek" column, which is an integer year*52+week
# Produces a dataframe with zero rows for missing weeks
#
completeZeroWeekly <- function (data) {

  firstweek = as.integer(data$yearweek[1])
  lastweek = as.integer(data$yearweek[nrow(data)])
  weeks = data.frame('yearweek'=c(firstweek:lastweek))
  completedata <- merge (data, weeks, all=TRUE)
  completedata[is.na(completedata)] <- 0
  return (completedata)
}

# Merge two dataframes with weekly data, filling holes with 0
#
# Both dataframes should have a "yearweek" column,
# which is an integer year*52+week
#
mergeWeekly <- function (d1, d2) {

  d = completeZeroWeekly (merge (d1, d2, all=TRUE))

  return (d)
}

# Complete a monthly dataframe with zero for missing months
#
# Gets as input a dataframe with montly data. It hast to
# include a "id" column, which is an integer year*12+month
# Produces a dataframe with zero rows for missing months
#
completeZeroMonthly <- function (data) {

  firstmonth = as.integer(data$id[1])
  lastmonth = as.integer(data$id[nrow(data)])
  months = data.frame('id'=c(firstmonth:lastmonth))
  completedata <- merge (data, months, all=TRUE)
  completedata[is.na(completedata)] <- 0
  return (completedata)
}

# Merge two dataframes with monthly data, filling holes with 0
#
# Both dataframes should have a "id" column,
# which is an integer year*12+week
#
mergeMonthly <- function (d1, d2) {

  d = completeZeroMonthly (merge (d1, d2, all=TRUE))

  return (d)
}

##
## toTextDate: convert two vectors with integers for year, month into
##  a vector with text
##
## Example: 2012, 2 -> Feb 2012
##
toTextDate <- function (year, month) {
  abb.months <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
  text <- paste (abb.months[month], as.character(year))
  return (text)
}

##
## GetYear
##
## Get the year of a datetime object
##
## Year as four digits (eg: 2012)
##
GetYear <- function (time) {
  return (1900 + as.POSIXlt(time)$year)
}

##
## GetMonth
##
## Get the month of a datetime object
##
## Month as an integer 0:11 (eg: Jan is 0)
##
GetMonth <- function (time) {
  return (as.POSIXlt(time)$mon)
}


#
# Plot several columns of a timeserie
#
#  data: data frame to plot
#  columns: names of the columns in data frame to plot
#  labels: strings to show as labels
#

## plotTimeSerieWeekN <- function (data, columns, filename, labels=columns) {

##   pdffilename <- paste (c(filename, ".pdf"), collapse='')
##   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
##   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')
  
##   # Build label for Y axis
##   label <- ""
##   for (col in 1:length(columns)) {
##     if (col != 1) {
##       label <- paste (c(label, " / "), collapse='')
##     }
##     label = paste (c(label, labels[col], " (", colors[col] ,")"),
##       collapse='')
##   }
  
##   # Regular plot
##   pdf(file=pdffilename, height=3.5, width=5)
##   timeserie <- ts (data[columns[1]],
##                    start=c(data$year[1],data$week[1]), frequency=52)
##   ts.plot (timeserie, col=colors[1], ylab=label)
##   if (length (columns) > 1) {
##     for (col in 2:length(columns)) {
##       timeserie <- ts (data[columns[col]],
##                        start=c(data$year[1],data$week[1]), frequency=52)
##       lines (timeserie, col=colors[col])
##     }
##   }
##   dev.off()

# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
## }

#
# Plot several columns of a timeserie
#
#  data: data frame to plot
#  columns: names of the columns in data frame to plot
#  labels: strings to show as labels
#

## plotTimeSerieMonthN <- function (data, columns, filename, labels=columns) {

##   pdffilename <- paste (c(filename, ".pdf"), collapse='')
##   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
##   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')
  
##   # Build label for Y axis
##   label <- ""
##   for (col in 1:length(columns)) {
##     if (col != 1) {
##       label <- paste (c(label, " / "), collapse='')
##     }
##     label = paste (c(label, labels[col], " (", colors[col] ,")"),
##       collapse='')
##   }
  
##   # Regular plot
##   pdf(file=pdffilename, height=3.5, width=5)
##   timeserie <- ts (data[columns[1]],
##                    start=c(data$year[1],data$month[1]), frequency=12)
##   ts.plot (timeserie, col=colors[1], ylab=label)
##   if (length (columns) > 1) {
##     for (col in 2:length(columns)) {
##       timeserie <- ts (data[columns[col]],
##                        start=c(data$year[1],data$month[1]), frequency=12)
##       lines (timeserie, col=colors[col])
##     }
##   }
##   dev.off()

# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
## }

## plotTimeSerieYearN <- function (data, columns, filename, labels=columns) {

##   pdffilename <- paste (c(filename, ".pdf"), collapse='')
##   pdffilenamelog <- paste (c(filename, "-log.pdf"), collapse='')
##   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
##   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')

##   # Build label for Y axis
##   label <- ""
##   for (col in 1:length(columns)) {
##     if (col != 1) {
##       label <- paste (c(label, " / "), collapse='')
##     }
##     label = paste (c(label, labels[col], " (", colors[col] ,")"),
##       collapse='')
##   }
  
##   timeserie <- ts (data[columns], start=data$year[1])
##   ## Regular plot
##   pdf(file=pdffilename, height=3.5, width=5)
##   ts.plot (timeserie, gpars=list(col=colors, ylab=label))
##   dev.off()
##   ## Log10 plot
##   pdf(file=pdffilenamelog, height=3.5, width=5)
##   ts.plot (log10(timeserie), gpars=list(col=colors, ylab=label))
##   dev.off()
  
  
# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
## }


#
# Plot histogram and density of probability for data frame (single column)
#
plotHistogramTime <- function (data, filename, label, title='') {

  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdf(pdffilename, height=5, width=5)
#  hist(data, prob= T, breaks='FD', col=blues[3], xlab = label, main = title)
  hist(data, freq=TRUE, breaks=15, col="orange", xlab = label, main = title)
#  lines(density(data), col=reds[3], lwd = 2)
  dev.off()
}
#library(vioplot)

#
# Plot boxplot for data frame
#
plotBoxPlot <- function (data, filename, label = '', title = '') {
  
  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdf(pdffilename, height=10, width=2)
  boxplot(data, col = greens[2], main = title, ylab = "days", xlab = label)
  # Mark top 3 outliers
  #top3 = rev(sort(data))[1:3]
  #print(top3)
  #text(rep(1,3), y = top3, label = paste(top3, 'days'), pos = 4)
  dev.off()
}

#
# Plot distribution of times
#
# Plots several charts:
#  - Histogram and density of probability for all tickets
#  - Histogram and density of probability for quickly closed tickets
#  - Histogram and density of probability for slowly closed tickets
# Threshold is for splitting in quick/slow (in days)
#
## plotTimeDist <- function (data, filename, unit = 'days', threshold = 30,
##                           variable = 'Time') {

##   label <- paste (c(variable, ' (', unit, ')'), collapse='')
##   # All tickets
##   plotHistogramTime (data, filename, label)
##   plotBoxPlot (data, paste (c (filename, '-boxplot'), collapse=''))
##   # Quickly closed tickets
##   quickly <- data[data <= threshold]
##   if (length(quickly) > 0) {
##     plotHistogramTime (quickly, paste (c (filename, '-quick'), collapse=''),
##                        label)
##     plotBoxPlot (quickly, paste (c (filename, '-quick-boxplot'), collapse=''))
##   }
##   # Slowly closed tickets
##   slowly <- data[data > threshold]
##   if (length(slowly) > 0) {
##     plotHistogramTime (slowly, paste (c (filename, '-slow'), collapse=''),
##                        label)
##     plotBoxPlot (slowly, paste (c (filename, '-slow-boxplot'), collapse=''))
##   }
## #  pdf(paste (c (filename, '-vioplot.pdf'), collapse=''), height=10, width=4)
## #  vioplot(data, quickly, slowly, col='gold', varwidth=TRUE)
## #  dev.off()
## }

## #
## # Plot time distributions and boxplots for time to fix in all years
## #
## plotTimeDistYear <- function (data, filename) {
##   for (year in data$year_open[1] : data$year_open[nrow(data)]) {
##     filename = paste(c(filename, '-',year), collapse='')
##     yearData <- data[data$year_open == year,]
##     plotTimeDist (yearData$ttofixm, filename, 'minutes',
##                   variable = 'Time to fix, first close')
##   }
## }

##
## Produce charts in several formats
##
produce.charts <- function (chart, filename, height = 4, width = 4) {
  if (! is.null(filename)) {
    pdffilename <- paste (c(filename, ".pdf"), collapse='')
    pdf(file=pdffilename, height=height, width=width)
    print (chart)
    dev.off()
    jpegfilename <- paste (c(filename, ".jpeg"), collapse='')
    jpeg(file=jpegfilename, height=height*75, width=width*75, quality=90)
    print (chart)
    dev.off()
  } else {
    print (chart)
  }
}

##
## binplot.3d
##
## Plot a bin in 3D, using rgl
## Code extracted from the rgl 3D histogram demo
##
binplot.3d <- function(x,y,z,alpha=1,topcol="red",sidecol="#aaaaaa")
{
  save <- par3d(skipRedraw=TRUE)
  on.exit(par3d(save))
  
  x1<-c(rep(c(x[1],x[2],x[2],x[1]),3),rep(x[1],4),rep(x[2],4))
  z1<-c(rep(0,4),rep(c(0,0,z,z),4))
  y1<-c(y[1],y[1],y[2],y[2],rep(y[1],4),rep(y[2],4),rep(c(y[1],y[2],y[2],y[1]),2))
  x2<-c(rep(c(x[1],x[1],x[2],x[2]),2),rep(c(x[1],x[2],rep(x[1],3),rep(x[2],3)),2))
  z2<-c(rep(c(0,z),4),rep(0,8),rep(z,8) )
  y2<-c(rep(y[1],4),rep(y[2],4),rep(c(rep(y[1],3),rep(y[2],3),y[1],y[2]),2) )
  rgl.quads(x1,z1,y1,col=rep(sidecol,each=4),alpha=alpha)
  rgl.quads(c(x[1],x[2],x[2],x[1]),rep(z,4),c(y[1],y[1],y[2],y[2]),
            col=rep(topcol,each=4),alpha=1) 
  rgl.lines(x2,z2,y2,col="#000000")
}

##
## hist3d
##
## Plot a 3D histogram
## Code based in the rgl 3D histogram demo
##
hist3d<-function(x,y=NULL,x.nclass="auto",y.nclass="auto",alpha=1,
                 cols=c("green","red","blue"),y.scale=200, z.scale=5)
{
  if (!is.numeric(y)) {
    values.y <- sort(unique(y))
    subst <- 0
    for (value in values.y) {
      subst <- subst + 1
      y[y==value] <- subst * y.scale
    }
    if (y.nclass == "auto") {
      y.nclass <- length(values.y)
    }
  }
  xy <- xy.coords(x,y)
  x <- xy$x
  if (x.nclass == "auto") {
    x.nclass<-ceiling(sqrt(nclass.Sturges(x)))
    }
  y <- xy$y
  breaks.x <- seq(min(x)-1,max(x)+1, length=(x.nclass+1))
  breaks.y <- seq(min(y)-1,max(y)+1,length=(y.nclass+1))
  z<-matrix(0,(x.nclass),(y.nclass))
  save <- par3d(skipRedraw=TRUE)
  on.exit(par3d(save))
  for (i in 1:x.nclass) 
  {
    for (j in 1:y.nclass) 
    {
      z[i, j] <- sum(x < breaks.x[i+1] & y < breaks.y[j+1] & 
        x >= breaks.x[i] & y >= breaks.y[j])
      binplot.3d(c(breaks.x[i],breaks.x[i+1]),c(breaks.y[j],breaks.y[j+1]),
                 z.scale*z[i,j],alpha=alpha,topcol=cols[j],sidecol=cols[j])
    }
  }
}


##
## Generic JSON function for using it in hierarchies of objects that need it
##
setGeneric (
 name= "JSON",
 def=function(.Object,...){standardGeneric("JSON")}
 )

##
## Generic Plot function for using it in hierarchies of objects that need it
##
setGeneric (
  name= "Plot",
  def=function(.Object,...){standardGeneric("Plot")}
  )

##
## Generic PlotDist function for using it in hierarchies of objects that need it
##
setGeneric (
 name= "PlotDist",
 def=function(object,...){standardGeneric("PlotDist")}
 )

##
## Code for producing JSON files suitable for vizGrimoire.JS
##
## All of this should still be re-coded as classes, but is here
## now for convenience, as a first step to support vizGrimoire.JS
##
library(rjson)

##
## Create a JSON file with some R object
##
createJSON <- function (data, filename) {
   sink(filename)
   cat(toJSON(data))
   sink()
}

evol_commits <- function(granularity){
  #Commits evolution

  q<- paste("select m.id as id,
                  m.year as year,
                  m.month as month,
                  DATE_FORMAT(m.date, '%b %Y') as date,
                  IFNULL(pm.commits, 0) as commits
           from   months m
           left join(
                  select year(s.date) as year, 
                         month(s.date) as month, 
                         count(distinct(s.id)) as commits
                  from   scmlog s 
                  group by year(s.date),
                         month(s.date)
                  order by year(s.date),
                         month(s.date) ) as pm
           on (
                  m.year = pm.year and
                  m.month = pm.month);")

  query <- new ("Query", sql = q)
  data_commits <- run(query)
  return (data_commits)
}


evol_committers <- function(granularity){
  #Committers evolution
  q <- paste ("select m.id as id,
                  m.year as year,
                  m.month as month,
                  DATE_FORMAT(m.date, '%b %Y') as date,
                  IFNULL(pm.committers, 0) as committers
           from   months m
           left join(
                  select year(s.date) as year, 
                         month(s.date) as month, 
                         count(distinct(s.committer_id)) as committers
                  from   scmlog s 
                  group by year(s.date),
                         month(s.date)
                  order by year(s.date),
                         month(s.date) ) as pm
           on (
                  m.year = pm.year and
                  m.month = pm.month);")

  query <- new ("Query", sql = q)
  data_committers <- run(query)
  return (data_committers)
}

evol_authors <- function(granularity){
	# Authors evolution
	q <- paste ("select m.id as id,
					m.year as year,
					m.month as month,
					DATE_FORMAT(m.date, '%b %Y') as date,
					IFNULL(pm.authors, 0) as authors
					from   months m
					left join(
					select year(s.date) as year, 
					month(s.date) as month, 
					count(distinct(s.author_id)) as authors
					from   scmlog s 
					group by year(s.date),
					month(s.date)
					order by year(s.date),
					month(s.date) ) as pm
					on (
					m.year = pm.year and
					m.month = pm.month);")
	
        query <- new ("Query", sql = q)
        data_authors <- run(query)
	return (data_authors)
}



evol_files <- function(granularity){

  #Files per month
  q <- paste("select m.id as id,
                  m.year as year,
                  m.month as month,
                  DATE_FORMAT(m.date, '%b %Y') as date,
                  IFNULL(pm.files, 0) as files
           from   months m
           left join(
                  select year(s.date) as year, 
                         month(s.date) as month, 
                         count(distinct(a.file_id)) as files
                  from   scmlog s, 
                         actions a
                  where  a.commit_id = s.id
                  group by year(s.date),
                         month(s.date)
                  order by year(s.date),
                         month(s.date) ) as pm
           on (
                  m.year = pm.year and
                  m.month = pm.month);")


  query <- new ("Query", sql = q)
  data_files <- run(query)
  return (data_files)
}


evol_branches <- function(granularity){

  #Branches per month
  q <- paste("select m.id as id,
                  m.year as year,
                  m.month as month,
                  DATE_FORMAT(m.date, '%b %Y') as date,
                  IFNULL(pm.branches, 0) as branches
           from   months m
           left join(
                  select year(s.date) as year, 
                         month(s.date) as month, 
                         count(distinct(a.branch_id)) as branches
                  from   scmlog s, 
                         actions a
                  where  a.commit_id = s.id
                  group by year(s.date),
                         month(s.date)
                  order by year(s.date),
                         month(s.date) ) as pm
           on (     
                  m.year = pm.year and
                  m.month = pm.month);")

  query <- new ("Query", sql = q)
  data_branches <- run(query)
  return (data_branches)
}


evol_repositories <- function(granularity) {

  # Repositories per month
  q <- paste("select m.id as id,
                  m.year as year,
                  m.month as month,
                  DATE_FORMAT(m.date, '%b %Y') as date,
                  IFNULL(pm.repositories, 0) as repositories
           from   months m
           left join(
                  select year(s.date) as year,
                         month(s.date) as month,
                         count(distinct(s.repository_id)) as repositories
                  from   scmlog s
                  group by year(s.date),
                         month(s.date)
                  order by year(s.date),
                         month(s.date) ) as pm
           on (
                  m.year = pm.year and
                  m.month = pm.month);")
  query <- new ("Query", sql = q)
  data_repositories <- run(query)
  return (data_repositories)
}

evol_info_data <- function() {

	# Get some general stats from the database
	##
	q <- paste("SELECT count(id) as commits, 
				count(distinct(committer_id)) as committers, 
				count(distinct(author_id)) as authors, 
				DATE_FORMAT (min(date), '%Y-%m-%d') as first_date, 
				DATE_FORMAT (max(date), '%Y-%m-%d') as last_date 
				FROM scmlog;")
        query <- new ("Query", sql = q)
        data1 <- run(query)
	query <- new("Query",
                     sql = "SELECT count(distinct(name)) as branches from branches")
	data2 <- run(query)
	query <- new("Query",
                     sql = "SELECT count(distinct(file_name)) as files from files")
	data3 <- run(query)
        query <- new("Query",
                     sql = "SELECT count(distinct(uri)) as repositories from repositories")
	data4 <- run(query)
        query <- new("Query",
                     sql = "SELECT count(*) as actions from actions")
	data5 <- run(query)
	agg_data = merge(data1, data2)
	agg_data = merge(agg_data, data3)
	agg_data = merge(agg_data, data4)
	agg_data = merge(agg_data, data5)
	return (agg_data)
}

top_committers <- function(days = 0) {
  if (days == 0 ) {
    q <- "SELECT count(s.id) as commits, p.email as developer
          FROM scmlog s JOIN people p ON p.id=s.committer_id 
	  GROUP BY p.email ORDER BY commits DESC 
	  LIMIT 10;"
  } else {
    query <- new("Query",
                 sql = "SELECT @maxdate:=max(date) from scmlog limit 1")
    data <- run(query)
    q <- paste("SELECT count(s.id) as commits, p.email as developer
	        FROM scmlog s JOIN people p ON p.id=s.committer_id
		WHERE DATEDIFF(@maxdate,date)<",days," 
	        GROUP BY p.email ORDER BY commits DESC 
	        LIMIT 10;")
  }
  query <- new("Query", sql = q)
  data <- run(query)
  return (data)	
}

top_files_modified <- function() {
  q <- paste("select file_name, count(commit_id) as modifications 
	      from action_files a join files f on a.file_id = f.id 
	      where action_type='M' group by f.id 
	      order by modifications desc limit 10; ")	
  query <- new("Query", sql = q)
  data <- run(query)
  return (data)	
}

##
## Top ticket closers
##
top_closers <- function(days = 0, closed_condition) {
  if (days == 0 ) {
    q <- paste("SELECT p.user_id as developer, count(c.id) as closed 
		FROM changes c JOIN people p ON c.changed_by = p.id 
		WHERE ", closed_condition, " 
		GROUP BY changed_by ORDER BY closed DESC LIMIT 10;")	
  } else {
    query <- new ("Query",
                  sql = "SELECT @maxdate:=max(changed_on) from changes limit 1")
    data <- run(query)
    q <- paste("SELECT p.user_id as developer, count(c.id) as closed 
		FROM changes c JOIN people p ON c.changed_by = p.id 
		WHERE ", closed_condition, " 
		AND c.id in (select id from changes where DATEDIFF(@maxdate,changed_on)<",days,") 
		GROUP BY changed_by ORDER BY closed DESC LIMIT 10;")		
  }
  query <- new ("Query", sql = q)
  data <- run(query)
  return (data)	
}
