## Copyright (C) 2012, 2013 Bitergia
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details. 
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
##
## This file is a part of the vizGrimoire R package
##  (an R library for the MetricsGrimoire and vizGrimoire systems)
##
## Auxiliary.R
##
## Auxiliary code for the classes in the package
##
## Authors:
##   Jesus M. Gonzalez-Barahona <jgb@bitergia.com>
##   Daniel Izquierdo <dizquierdo@bitergia.com>
##   Alvaro del Castillo <acs@bitergia.com>
##
## Note: this file should be (alphabetically) the first one in the list
##  of files with R source code for the package. It seems that files are
##  run in alphabetic order, and this one includes facilities needed by
##  the rest. An alternative would be to use a "Collate" field in the
##  DESCRIPTION file.
##

## Get arguments from the command line
##
##  - dbschema: MySQL database schema to use, generated by CVSAnalY2
##  - user: MySQL user with permissions to access the schema
##  - passwd: password corresponding to user
##  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
##      (in fact, first day after the period)
##  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
##
##
ConfFromCommandLine <- function () {
  ## Get command line args, and produce variables for the script
  args <- commandArgs(trailingOnly = TRUE)

  if (length(args) > 3) {
    enddate <- args[4]
  } else {
    enddate <- "2100-01-01"
  }
  enddatesplit <- strsplit(enddate,'-')
  endyear <- enddatesplit[[1]][1]
  endmonth <- enddatesplit[[1]][2]
  enddate <- paste (c("'", enddate, "'"), collapse='')
  
  if (length(args) > 4) {
    startdate <- args[5]
  } else {
    startdate <- "1900-01-01"
  }
  startdatesplit <- strsplit(startdate,'-')
  startyear <- startdatesplit[[1]][1]
  startmonth <- startdatesplit[[1]][2]
  startdate <- paste (c("'", startdate, "'"), collapse='')

  conf <- list (database = args[1],
                user = args[2],
                password = args[3],
                startdate = startdate,
                enddate = enddate)
  return (conf)
}

library(optparse)

ConfFromOptParse <- function (datasource="") {
	option_list <- list(			
			make_option(c("-d", "--database"), dest="database", 
					help="Database with data"),
                        make_option(c("-i", "--identities"), dest="identities_db",
                                        help="Database with unique identities and affiliations"),
			make_option(c("-u", "--dbuser"), dest="dbuser", 
					help="Database user", default="root"),
			make_option(c("-p", "--dbpass"), dest="dbpassword", 
					help="Database user password", default=""),			
			make_option(c("-r", "--reports"), dest="reports", default="",
					help="Reports to be generated (repositories, companies)"),
			make_option(c("-s", "--start"), dest="startdate", 
					help="Start date for the report", default="1900-01-01"),
                        make_option(c("-g", "--granularity"), dest="granularity",
                                        help="Granularity for the report (months, weeks)", default="months"),
			make_option(c("-e", "--end"), dest="enddate", 
					help="End date for the report", default="2100-01-01"),
          		make_option(c("-o", "--destination"), dest="destination", 
					help="Destination directory", default="data/json")
	)	
	if (datasource == 'its') {
		option_list = c(option_list, make_option(
			c("-t", "--type"), dest="backend", 
			help="Type of backend: bugzilla, allura, jira, github", 
			default="bugzilla"));	
	}
	parser <- OptionParser(usage = "%prog [options]", option_list = option_list)
	options <- parse_args(parser)	
	if (is.null(options$database)) {		
		print_help(parser)
		stop("Database param is required")
	}
	enddatesplit <- strsplit(options$enddate,'-')
	endyear <- enddatesplit[[1]][1]
	endmonth <- enddatesplit[[1]][2]
        options$str_enddate <- options$enddate
	options$enddate <- paste (c("'", options$enddate, "'"), collapse='')
	
	startdatesplit <- strsplit(options$startdate,'-')
	startyear <- startdatesplit[[1]][1]
	startmonth <- startdatesplit[[1]][2]
        options$str_startdate <- options$startdate
	options$startdate <- paste (c("'", options$startdate, "'"), collapse='')

		
	return (options)
}

## Get arguments from parameters to this function
##
##  - dbschema: MySQL database schema to use, generated by CVSAnalY2
##  - user: MySQL user with permissions to access the schema
##  - passwd: password corresponding to user
##  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
##      (in fact, first day after the period)
##  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
##
##
ConfFromParameters <- function (dbschema, user = NULL, password = NULL,
                                host = "127.0.0.1", port = 3306,
                                group = NULL,
                                enddate = NULL, startdate = NULL) {
  if (is.null(enddate)) {
    enddate <- "2100-01-01"
  }
  enddate <- paste (c("'", enddate, "'"), collapse='')
  if (is.null(startdate)) {
    startdate <- "1900-01-01"
  }
  startdate <- paste (c("'", startdate, "'"), collapse='')

  conf <- list (database = dbschema,
                user = user,
                password = password,
                host = host,
                port = port,
                group = group,
                startdate = startdate,
                enddate = enddate)
  return (conf)
}

##
## Penalize scientific notation by 10 chars
##
options(scipen=10)

##
## Database-related classes & functions
##

library(RMySQL)
##
## Connect to the database and prepare...
##

SetDBChannel <- function (user=NULL, password=NULL, database,
                          host="127.0.0.1", port=3306,
                          group=NULL) {
  if (is.null(group)) {
    mychannel <<- dbConnect(MySQL(), user=user, password=password,
                            db=database, host=host, port=port)
  } else {
    mychannel <<- dbConnect(MySQL(), group=group,
                            db=database)
  }    
  dbGetQuery(mychannel, "SET NAMES 'utf8'")
}

##
## Close connection to the database
##

CloseDBChannel <- function () {
  dbDisconnect(mychannel)
}

##
## Find out kind of repository (bugzilla, launchpad, etc.) and
##  store it in common configuration list
##
FindoutRepoKind <- function () {
  q <- new ("Query", sql = "SELECT name FROM supported_trackers")
  kind <- run(q)$name[1]
  return (kind)
}

# Note use display.brewer.pal(...) to check colors
# example: display.brewer.pal(9, "Greens")
library(RColorBrewer)

blues = brewer.pal(5,'Blues')
reds = brewer.pal(5,'Reds')
greens = brewer.pal(5,'Greens')

#
# List of colors for plots
#
colors <- c("black", "green", "red", "blue", "orange", "brown")


# Complete a weekly dataframe with zero for missing weeks
#
# Gets as input a dataframe with weekly data. It hast to
# include a "yearweek" column, which is an integer year*52+week
# Produces a dataframe with zero rows for missing weeks
#
completeZeroWeekly <- function (data) {

  firstweek = as.integer(data$yearweek[1])
  lastweek = as.integer(data$yearweek[nrow(data)])
  weeks = data.frame('yearweek'=c(firstweek:lastweek))
  completedata <- merge (data, weeks, all=TRUE)
  completedata[is.na(completedata)] <- 0
  return (completedata)
}

# Merge two dataframes with weekly data, filling holes with 0
#
# Both dataframes should have a "yearweek" column,
# which is an integer year*52+week
#
mergeWeekly <- function (d1, d2) {

  d = completeZeroWeekly (merge (d1, d2, all=TRUE))

  return (d)
}

# Complete a monthly dataframe with zero for missing months
#
# Gets as input a dataframe with montly data. It hast to
# include a "id" column, which is an integer year*12+month
# Produces a dataframe with zero rows for missing months
#
completeZeroMonthly <- function (data) {

  #firstmonth = as.integer(data$id[1])
  firstmonth = 0
  lastmonth = as.integer(data$id[nrow(data)])
  months = data.frame('id'=c(firstmonth:lastmonth))
  completedata <- merge (data, months, all=TRUE)
  completedata[is.na(completedata)] <- 0
  return (completedata)
}

# Merge two dataframes with monthly data, filling holes with 0
#
# Both dataframes should have a "id" column,
# which is an integer year*12+week
#
mergeMonthly <- function (d1, d2) {

  d = completeZeroMonthly (merge (d1, d2, all=TRUE))

  return (d)
}

completeZeroPeriod <- function (data, nperiod, startdate, enddate){
    first = 0
    last = ceiling (difftime(as.POSIXlt(enddate), as.POSIXlt(startdate),units='days') / nperiod) - 1
    periods = data.frame('id'=c(first:last))
    completedata <- merge (data, periods, all=TRUE)
    completedata[is.na(completedata)] <- 0
    return (completedata)
}

##
## toTextDate: convert two vectors with integers for year, month into
##  a vector with text
##
## Example: 2012, 2 -> Feb 2012
##
toTextDate <- function (year, month) {
  abb.months <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
  text <- paste (abb.months[month], as.character(year))
  return (text)
}

##
## GetYear
##
## Get the year of a datetime object
##
## Year as four digits (eg: 2012)
##
GetYear <- function (time) {
  return (1900 + as.POSIXlt(time)$year)
}

##
## GetMonth
##
## Get the month of a datetime object
##
## Month as an integer 0:11 (eg: Jan is 0)
##
GetMonth <- function (time) {
  return (as.POSIXlt(time)$mon)
}

##
## GetWeek
##
## Get the week of a datetime object
##
## Week of the year as decimal number (00–53) as defined in ISO 8601. 
## If the week (starting on Monday) containing 1 January has four or 
## more days in the new year, then it is considered week 1. 
## Otherwise, it is the last week of the previous year, and the next week is week 1. 
## (Accepted but ignored on input.)
##
GetWeek  <- function (time) {
    return (format(time, "%V"))
}

## Group daily samples by selected period
completePeriod <- function (data, period, conf) {
        
    if (length(data) == 0) {
        data <- data.frame(id=numeric(0))
    }
    new_data <- completeZeroPeriod(data, period, conf$str_startdate, conf$str_enddate)
    new_data$week <- as.Date(conf$str_startdate) + new_data$id * period
    new_data$date  <- toTextDate(GetYear(new_data$week), GetMonth(new_data$week)+1)
    new_data[is.na(new_data)] <- 0
    new_data <- new_data[order(new_data$id), ]
        
    return (new_data)
}

GetPeriod <- function(period, date) {
    val = NULL
    
    if (!(period %in% c('weeks','months','years'))) 
        stop (paste("WRONG PERIOD", period))
    if (period == "weeks") val = GetWeek(date)
    else if (period == "months") val = GetMonth(date)
    else if (period == "years") val = GetYear(date)
    
    return (val)
}

GetDateText <- function(period, date) {
    val = NULL
    
    if (!(period %in% c('weeks','months','years'))) 
        stop (paste("WRONG PERIOD", period))
    if (period == "weeks") val = strftime(date, "%W %d %b %Y")
    else if (period == "months") val = strftime(date, "%d %b %Y")
    else if (period == "years") val = strftime(date, "%d %b %Y")
    
    return (val)
}

# Normalize JSON for all metrics
completePeriodMulti <- function(data, metrics, period,startdate, enddate) {    
    for (metric in metrics) {        
        metric_data <- data.frame(id=data$id,metric=data[[metric]])
        colnames(metric_data)[2]<-metric
        print(metric_data)      
        metric_data <- completePeriod2(metric_data, period, 
                conf$str_startdate, conf$str_enddate)
        if (!(exists('new_data'))) new_data <- metric_data
        else new_data <- merge(new_data, metric_data, all = TRUE)
    }
    print(new_data)
    return(new_data)    
}


completeZeroPeriodIdsYears <- function (data, start, end) {    
    last = end$year - start$year  + 1   
    samples <- list('id'=c(0:(last-1)))    
    
    new_date = start
    new_date$mday = 1
    new_date$mon = 0
    for (i in 1:last) {
        # convert to Date to remove DST from start of month
        samples$unixtime[i] = toString(as.numeric(as.POSIXlt(as.Date(new_date))))
        samples$date[i]=format(new_date, "%b %Y")
        samples$year[i]=(1900+new_date$year)*12
        new_date$year = new_date$year + 1
    }
    completedata <- merge (data, samples, all=TRUE)
    completedata[is.na(completedata)] <- 0        
    return(completedata)    
}


completeZeroPeriodIdsMonths <- function (data, start, end) {    
    start_month = ((1900+start$year)*12)+start$mon+1
    end_month =  ((1900+end$year)*12)+end$mon+1 
    last = end_month - start_month + 1 
    
    samples <- list('id'=c(0:(last-1)))
    new_date = start
    new_date$mday = 1    
    for (i in 1:last) {
        # convert to Date to remove DST from start of month
        samples$unixtime[i] = toString(as.numeric(as.POSIXlt(as.Date(new_date))))
        samples$date[i]=format(new_date, "%b %Y")
        samples$month[i]=((1900+new_date$year)*12)+new_date$mon+1
        new_date$mon = new_date$mon + 1
    }        
    completedata <- merge (data, samples, all=TRUE)
    completedata[is.na(completedata)] <- 0        
    return(completedata)    
}

#######################
# Code to count weeks as done by 
# MySQL using the function yearweek
#######################
library(ISOweek)
#Example of diff: number of weeks between 2010-05-27 and 2013-07-23 = 166. 

getISOWEEKYear <- function(date){
  #expected a date like '2013-12-01'
  isoweekdate <- date2ISOweek(date)
  year_week <- strsplit(isoweekdate, '-')
  year <- year_week[[1]][1]
  return (year)
}

getISOWEEKWeek <- function(date){
  #expected a date like '2013-12-01'
  isoweekdate <- date2ISOweek(date)
  year_week <- strsplit(isoweekdate, '-')
  week <- year_week[[1]][2]
  week <- strsplit(week, 'W')[[1]][2]
  return(week)
  
}

getMaxWeekYear <- function(year){
  #this will provide the maximum number of weeks for a given
  #year
  iso_year = year + 1
  final_date = ""
  day = 31
  while (iso_year > year){
    final_date = paste(year, "-12-", day, sep="")
    iso_year <- getISOWEEKYear(final_date)
    day = day - 1
  }
  
  max_week = getISOWEEKWeek(final_date)
  
  return (max_week)
}

diffISOWeekTime <- function(initdate, enddate){
  #diffweeks for 2013-07-23 and 2010-05-27
  #using typical difftime, there are 164 weeks, 
  #but there should be 166 if this is compared to the
  #yearweek function in mysql group.
  
  inityear = as.numeric(getISOWEEKYear(initdate))
  initweek = as.numeric(getISOWEEKWeek(initdate))
  endyear = as.numeric(getISOWEEKYear(enddate))
  endweek = as.numeric(getISOWEEKWeek(enddate))
  
  diffweeks = 0
  if (inityear == endyear){
    diffweeks = endweek - initweek + 1
  } else if (endyear > inityear) {
    for (i in inityear:endyear){
      if (i == inityear){
        #init of the loop
        diffweeks = diffweeks + as.numeric(getMaxWeekYear(i)) - initweek + 1
      } else if (i == endyear){
        # end of the loop
        diffweeks = diffweeks + endweek
      } else {
        # any year between inityear and endyear
        diffweeks = diffweeks + as.numeric(getMaxWeekYear(i))
      }
    }  
  } else {
    print ("Error, enddate < initdate")
  }

  return (diffweeks)  
}



completeZeroPeriodIdsWeeks <- function(data, start, end) {
  # this function fills with 0's those weeks with no data between
  # start and end for data. An initial sample is filled with all
  # information necessary and later merged with data.

  # number of total weeks (those are natural weeks starting on Monday)
  # This should behave in the same way as the yearweek function in MYSQL does
  # With this approach, periods of 9 days may imply up to three weeks 
  # (Sunday plus full week plus Monday).
  totalWeeks = diffISOWeekTime(start, end)
    
  inityear = as.numeric(getISOWEEKYear(start))
  initweek = as.numeric(getISOWEEKWeek(start))
  endyear = as.numeric(getISOWEEKYear(end))
  endweek = as.numeric(getISOWEEKWeek(end))

  samples <- list('id' = c(1:totalWeeks))
  cont = 1
  for (i in inityear:endyear){
    #
    for (j in 1:getMaxWeekYear(i)){
      if (inityear == endyear) {
        if ((j >= initweek) && (j <= endweek)){
          year = as.character(i)
          extra = ""
          if (j<10) extra = "0"
          week = paste(extra, as.character(j), sep="")
          isoweekdate = paste(year, "-W", week, "-1", sep="")
          normal_date = as.POSIXlt(as.Date(ISOweek2date(isoweekdate)))

          samples$unixtime[cont] = toString(as.numeric(normal_date))
          samples$date[cont] = format(normal_date, "%b %Y")
          samples$week[cont] = paste(year, week, sep="")
          cont = cont + 1
        }

      } else { 
        if ((i == inityear && j >= initweek) || (i == endyear && j <= endweek) || (i > inityear && i< endyear)){
          # same code as above, to be refactored...
          year = as.character(i)
          extra = ""
          if (j<10) extra = "0"
          week = paste(extra, as.character(j), sep="")
          isoweekdate = paste(year, "-W", week, "-1", sep="")
          normal_date = as.POSIXlt(as.Date(ISOweek2date(isoweekdate)))

          samples$unixtime[cont] = toString(as.numeric(normal_date))
          samples$date[cont] = format(normal_date, "%b %Y")
          samples$week[cont] = paste(year, week, sep="")
          cont = cont + 1
        }
      }
    }  
  }

  completedata <- merge(data, samples, all=TRUE)
  completedata[is.na(completedata)] <- 0
  return(completedata)
}


# Work in seconds as a future investment
completeZeroPeriodIdsDays <- function (data, start, end) {        
    # units should be one of “auto”, “secs”, “mins”, “hours”, “days”, “weeks”
    last = ceiling (difftime(end, start,units=period))               
    samples <- list('id'=c(0:(last-1))) 
    lastdate = start
    start_dst = start$isdst
    dst = start_dst
    dst_offset_hour = 0
    hour.secs = 60*60
    day.secs = hour.secs*24
    for (i in 1:last) {        
        unixtime = as.numeric(start)+((i-1)*day.secs)
        new_date = as.POSIXlt(unixtime,origin="1970-01-01") 
        if (new_date$isdst != dst) {
            dst = new_date$isdst            
            if (dst == start_dst) dst_offset_hour = 0
            else if (start_dst == 0) dst_offset_hour = -hour.secs
            else if (start_dst == 1) dst_offset_hour = hour.secs
        }
        unixtime = unixtime + dst_offset_hour
        lastdate = as.POSIXlt(unixtime, origin="1970-01-01")
        samples$unixtime[i] = toString(unixtime)
        # samples$datedbg[i]=format(lastdate,"%H:%M %d-%m-%y")
        samples$date[i]=format(lastdate, "%b %Y")
    }
    completedata <- merge (data, samples, all=TRUE)
    completedata[is.na(completedata)] <- 0
    return (completedata)
}

completeZeroPeriodIds <- function (data, period, startdate, enddate){           
    start = as.POSIXlt(startdate)
    end = as.POSIXlt(enddate)    
    if (period == "days") {
        return (completeZeroPeriodIdsDays(data, start, end))
    }    
    else if (period == "weeks") {
        return (completeZeroPeriodIdsWeeks(data, start, end))
    }
    else if (period == "months") {
        return (completeZeroPeriodIdsMonths(data, start, end))
    }
    else if (period == "years") {
        return (completeZeroPeriodIdsYears(data, start, end))
    } 
    else {
        stop (paste("Unknow period", period))
    } 
    
}

completePeriodIds <- function (data, period, conf) {    
    if (length(data) == 0) {
        #data is initialized, although nrow(data) is still 0
        data <- data.frame(id=numeric(0))
    }
    new_data <- completeZeroPeriodIds(data, period, conf$str_startdate, conf$str_enddate)
    new_data[is.na(new_data)] <- 0
    new_data <- new_data[order(new_data$id), ]    
    return (new_data)
}

#
# Plot several columns of a timeserie
#
#  data: data frame to plot
#  columns: names of the columns in data frame to plot
#  labels: strings to show as labels
#

## plotTimeSerieWeekN <- function (data, columns, filename, labels=columns) {

##   pdffilename <- paste (c(filename, ".pdf"), collapse='')
##   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
##   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')
  
##   # Build label for Y axis
##   label <- ""
##   for (col in 1:length(columns)) {
##     if (col != 1) {
##       label <- paste (c(label, " / "), collapse='')
##     }
##     label = paste (c(label, labels[col], " (", colors[col] ,")"),
##       collapse='')
##   }
  
##   # Regular plot
##   pdf(file=pdffilename, height=3.5, width=5)
##   timeserie <- ts (data[columns[1]],
##                    start=c(data$year[1],data$week[1]), frequency=52)
##   ts.plot (timeserie, col=colors[1], ylab=label)
##   if (length (columns) > 1) {
##     for (col in 2:length(columns)) {
##       timeserie <- ts (data[columns[col]],
##                        start=c(data$year[1],data$week[1]), frequency=52)
##       lines (timeserie, col=colors[col])
##     }
##   }
##   dev.off()

# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
## }

#
# Plot several columns of a timeserie
#
#  data: data frame to plot
#  columns: names of the columns in data frame to plot
#  labels: strings to show as labels
#

## plotTimeSerieMonthN <- function (data, columns, filename, labels=columns) {

##   pdffilename <- paste (c(filename, ".pdf"), collapse='')
##   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
##   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')
  
##   # Build label for Y axis
##   label <- ""
##   for (col in 1:length(columns)) {
##     if (col != 1) {
##       label <- paste (c(label, " / "), collapse='')
##     }
##     label = paste (c(label, labels[col], " (", colors[col] ,")"),
##       collapse='')
##   }
  
##   # Regular plot
##   pdf(file=pdffilename, height=3.5, width=5)
##   timeserie <- ts (data[columns[1]],
##                    start=c(data$year[1],data$month[1]), frequency=12)
##   ts.plot (timeserie, col=colors[1], ylab=label)
##   if (length (columns) > 1) {
##     for (col in 2:length(columns)) {
##       timeserie <- ts (data[columns[col]],
##                        start=c(data$year[1],data$month[1]), frequency=12)
##       lines (timeserie, col=colors[col])
##     }
##   }
##   dev.off()

# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
## }

## plotTimeSerieYearN <- function (data, columns, filename, labels=columns) {

##   pdffilename <- paste (c(filename, ".pdf"), collapse='')
##   pdffilenamelog <- paste (c(filename, "-log.pdf"), collapse='')
##   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
##   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')

##   # Build label for Y axis
##   label <- ""
##   for (col in 1:length(columns)) {
##     if (col != 1) {
##       label <- paste (c(label, " / "), collapse='')
##     }
##     label = paste (c(label, labels[col], " (", colors[col] ,")"),
##       collapse='')
##   }
  
##   timeserie <- ts (data[columns], start=data$year[1])
##   ## Regular plot
##   pdf(file=pdffilename, height=3.5, width=5)
##   ts.plot (timeserie, gpars=list(col=colors, ylab=label))
##   dev.off()
##   ## Log10 plot
##   pdf(file=pdffilenamelog, height=3.5, width=5)
##   ts.plot (log10(timeserie), gpars=list(col=colors, ylab=label))
##   dev.off()
  
  
# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
## }


#
# Plot histogram and density of probability for data frame (single column)
#
plotHistogramTime <- function (data, filename, label, title='') {

  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdf(pdffilename, height=5, width=5)
#  hist(data, prob= T, breaks='FD', col=blues[3], xlab = label, main = title)
  hist(data, freq=TRUE, breaks=15, col="orange", xlab = label, main = title)
#  lines(density(data), col=reds[3], lwd = 2)
  dev.off()
}
#library(vioplot)

#
# Plot boxplot for data frame
#
plotBoxPlot <- function (data, filename, label = '', title = '') {
  
  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdf(pdffilename, height=10, width=2)
  boxplot(data, col = greens[2], main = title, ylab = "days", xlab = label)
  # Mark top 3 outliers
  #top3 = rev(sort(data))[1:3]
  #print(top3)
  #text(rep(1,3), y = top3, label = paste(top3, 'days'), pos = 4)
  dev.off()
}

#
# Plot distribution of times
#
# Plots several charts:
#  - Histogram and density of probability for all tickets
#  - Histogram and density of probability for quickly closed tickets
#  - Histogram and density of probability for slowly closed tickets
# Threshold is for splitting in quick/slow (in days)
#
## plotTimeDist <- function (data, filename, unit = 'days', threshold = 30,
##                           variable = 'Time') {

##   label <- paste (c(variable, ' (', unit, ')'), collapse='')
##   # All tickets
##   plotHistogramTime (data, filename, label)
##   plotBoxPlot (data, paste (c (filename, '-boxplot'), collapse=''))
##   # Quickly closed tickets
##   quickly <- data[data <= threshold]
##   if (length(quickly) > 0) {
##     plotHistogramTime (quickly, paste (c (filename, '-quick'), collapse=''),
##                        label)
##     plotBoxPlot (quickly, paste (c (filename, '-quick-boxplot'), collapse=''))
##   }
##   # Slowly closed tickets
##   slowly <- data[data > threshold]
##   if (length(slowly) > 0) {
##     plotHistogramTime (slowly, paste (c (filename, '-slow'), collapse=''),
##                        label)
##     plotBoxPlot (slowly, paste (c (filename, '-slow-boxplot'), collapse=''))
##   }
## #  pdf(paste (c (filename, '-vioplot.pdf'), collapse=''), height=10, width=4)
## #  vioplot(data, quickly, slowly, col='gold', varwidth=TRUE)
## #  dev.off()
## }

## #
## # Plot time distributions and boxplots for time to fix in all years
## #
## plotTimeDistYear <- function (data, filename) {
##   for (year in data$year_open[1] : data$year_open[nrow(data)]) {
##     filename = paste(c(filename, '-',year), collapse='')
##     yearData <- data[data$year_open == year,]
##     plotTimeDist (yearData$ttofixm, filename, 'minutes',
##                   variable = 'Time to fix, first close')
##   }
## }

##
## Produce charts in several formats
##
produce.charts <- function (chart, filename, height = 4, width = 4) {
  if (! is.null(filename)) {
    pdffilename <- paste (c(filename, ".pdf"), collapse='')
    pdf(file=pdffilename, height=height, width=width)
    print (chart)
    dev.off()
    jpegfilename <- paste (c(filename, ".jpeg"), collapse='')
    jpeg(file=jpegfilename, height=height*75, width=width*75, quality=90)
    print (chart)
    dev.off()
  } else {
    print (chart)
  }
}

##
## binplot.3d
##
## Plot a bin in 3D, using rgl
## Code extracted from the rgl 3D histogram demo
##
binplot.3d <- function(x,y,z,alpha=1,topcol="red",sidecol="#aaaaaa")
{
  save <- par3d(skipRedraw=TRUE)
  on.exit(par3d(save))
  
  x1<-c(rep(c(x[1],x[2],x[2],x[1]),3),rep(x[1],4),rep(x[2],4))
  z1<-c(rep(0,4),rep(c(0,0,z,z),4))
  y1<-c(y[1],y[1],y[2],y[2],rep(y[1],4),rep(y[2],4),rep(c(y[1],y[2],y[2],y[1]),2))
  x2<-c(rep(c(x[1],x[1],x[2],x[2]),2),rep(c(x[1],x[2],rep(x[1],3),rep(x[2],3)),2))
  z2<-c(rep(c(0,z),4),rep(0,8),rep(z,8) )
  y2<-c(rep(y[1],4),rep(y[2],4),rep(c(rep(y[1],3),rep(y[2],3),y[1],y[2]),2) )
  rgl.quads(x1,z1,y1,col=rep(sidecol,each=4),alpha=alpha)
  rgl.quads(c(x[1],x[2],x[2],x[1]),rep(z,4),c(y[1],y[1],y[2],y[2]),
            col=rep(topcol,each=4),alpha=1) 
  rgl.lines(x2,z2,y2,col="#000000")
}

##
## hist3d
##
## Plot a 3D histogram
## Code based in the rgl 3D histogram demo
##
hist3d<-function(x,y=NULL,x.nclass="auto",y.nclass="auto",alpha=1,
                 cols=c("green","red","blue"),y.scale=200, z.scale=5)
{
  if (!is.numeric(y)) {
    values.y <- sort(unique(y))
    subst <- 0
    for (value in values.y) {
      subst <- subst + 1
      y[y==value] <- subst * y.scale
    }
    if (y.nclass == "auto") {
      y.nclass <- length(values.y)
    }
  }
  xy <- xy.coords(x,y)
  x <- xy$x
  if (x.nclass == "auto") {
    x.nclass<-ceiling(sqrt(nclass.Sturges(x)))
    }
  y <- xy$y
  breaks.x <- seq(min(x)-1,max(x)+1, length=(x.nclass+1))
  breaks.y <- seq(min(y)-1,max(y)+1,length=(y.nclass+1))
  z<-matrix(0,(x.nclass),(y.nclass))
  save <- par3d(skipRedraw=TRUE)
  on.exit(par3d(save))
  for (i in 1:x.nclass) 
  {
    for (j in 1:y.nclass) 
    {
      z[i, j] <- sum(x < breaks.x[i+1] & y < breaks.y[j+1] & 
        x >= breaks.x[i] & y >= breaks.y[j])
      binplot.3d(c(breaks.x[i],breaks.x[i+1]),c(breaks.y[j],breaks.y[j+1]),
                 z.scale*z[i,j],alpha=alpha,topcol=cols[j],sidecol=cols[j])
    }
  }
}


##
## Generic JSON function for using it in hierarchies of objects that need it
##
setGeneric (
 name= "JSON",
 def=function(.Object,...){standardGeneric("JSON")}
 )

##
## Generic Plot function for using it in hierarchies of objects that need it
##
setGeneric (
  name= "Plot",
  def=function(.Object,...){standardGeneric("Plot")}
  )

##
## Generic PlotDist function for using it in hierarchies of objects that need it
##
setGeneric (
 name= "PlotDist",
 def=function(object,...){standardGeneric("PlotDist")}
 )

##
## Code for producing JSON files suitable for vizGrimoire.JS
##
## All of this should still be re-coded as classes, but is here
## now for convenience, as a first step to support vizGrimoire.JS
##
library(rjson)

##
## Create a JSON file with some R object
##
createJSON <- function (data, filename) {
   sink(filename)
   cat(toJSON(data))
   sink()
}

##
## METAQUERIES
##

GetSQLGlobal <- function(date, fields, tables, filters, start, end) {        
    sql = paste ('SELECT ', fields)
    sql = paste(sql,'FROM', tables)
    sql = paste(sql,'WHERE',date,'>=',start,'AND',date,'<',end)
    if (filters != "") {
        if (regexpr("^[ ]*and", tolower(filters)) > 0 ) sql = paste(sql, filters)
        else sql = paste(sql,' AND ',filters)
    }
    return(sql)    
}

GetSQLPeriod <- function(period, date, fields, tables, filters, start, end) {
    
    kind = c('year','month','week','day')
    iso_8601_mode = 3
    if (period == 'day') {
        # Remove time so unix timestamp is start of day    
        sql = paste('SELECT UNIX_TIMESTAMP(DATE(',date,')) AS unixtime, ')
    } else if (period == 'week') {
        sql = paste('SELECT YEARWEEK(',date,',',iso_8601_mode,') AS week, ')
    } else if (period == 'month') {
        sql = paste('SELECT YEAR(',date,')*12+MONTH(',date,') AS month, ')
    }  else if (period == 'year') {
        sql = paste('SELECT YEAR(',date,')*12 AS year, ')
    } else {
        stop(paste("Wrong period",period))
    }
    # sql = paste(sql, 'DATE_FORMAT (',date,', \'%d %b %Y\') AS date, ')
    sql = paste(sql, fields)
    sql = paste(sql,'FROM', tables)
    sql = paste(sql,'WHERE',date,'>=',start,'AND',date,'<',end)
    if (filters != "") {
        if (regexpr("^[ ]*and", tolower(filters)) > 0 ) sql = paste(sql, filters)
        else sql = paste(sql,' AND ',filters)
    }    
    if (period == 'year') {
        sql = paste(sql,' GROUP BY YEAR(',date,')')
        sql = paste(sql,' ORDER BY YEAR(',date,')')
    }
    else if (period == 'month') {
        sql = paste(sql,' GROUP BY YEAR(',date,'),MONTH(',date,')')
        sql = paste(sql,' ORDER BY YEAR(',date,'),MONTH(',date,')')
    }
    else if (period == 'week') {
        sql = paste(sql,' GROUP BY YEARWEEK(',date,',',iso_8601_mode,') ')
        sql = paste(sql,' ORDER BY YEARWEEK(',date,',',iso_8601_mode,') ')        
    }
    else if (period == 'day') {
        sql = paste(sql,' GROUP BY YEAR(',date,'),DAYOFYEAR(',date,')')
        sql = paste(sql,' ORDER BY YEAR(',date,'),DAYOFYEAR(',date,')')                
    }
    else {
        stop(paste("PERIOD: ",period,' not supported'))
    }
    return(sql)
}


library(zoo) 

RollMean<-function(serie,s,l)
{ 
    #serie;data where you want to calculate rollmeans.
    #s<l; Periods of time.
    #function; draws rollmeans for two different periods of time. 
    ms<-rollapply(serie,s,mean)
    ml<-rollapply(serie,l,mean)
    w<-rep(0,l-1)
    v<-rep(0,s-1)
    mms<-c(v,ms)
    mml<-c(w,ml)
    scale<-c(min(mms):max(mms))
    #plot(mml, type="l", col="blue") 
    #lines(mms, type="l", col="red")
    means<-data.frame(mms,mml)
    return(means)
}

DiffRoll<-function(serie,s,l)
{
#serie=data s=time_period l=time_period s<l  
#This function gives the difference between short and long rollmean.
k<-l-s
ms<-rollapply(serie,s,mean)
ml<-rollapply(serie,l,mean)
short<-ms[-c(1:k)]
metric<-short-ml
central<-rep(0,length(metric))
#plot(metric, type="l", xlab="weeks", ylab="Short mean-Long mean", main="Rollmean signals")
#lines(central, type="l")
end<-data.frame(metric,central)
return(end)
}


ExpoAv<-function(serie,s,l)
#This function gives a type of moving average that is similar to a simple moving average, except that more weight is given to the latest data.
#serie= data to apply function 
#s= short period of time to apply moving average
#l= long period of time to apply moving average
{ alphas=2/(1+s)
 
  alphal=2/(1+l)
  
  short<-rollapply(serie,s,mean)
  long<-rollapply(serie,l,mean)
  
   getEMA2<-function(x,alpha){
    v<-vector()
    for (i in 1:length(x)){
      if (i==1){
        v[i]<-x[i]
               }
      else{
        v[i]<-alpha*x[i]+(1-alpha)*v[i-1]
          }
    }
    
  return(v)
}
  
  AS<-getEMA2(short,alphas)
  AL<-getEMA2(long,alphal)

  #plot(serie, type="l", col="black", lty=2,ylab="Commits", xlab="weeks", main="EMA")
  #lines(AL,type="l",col="blue")
  #lines(AS,type="l", col="red")
  #legend("topleft",col=c("red","blue","black"),lty=c(1,1,2) ,legend=c("Short","Long","commits"))
  w<-rep(0,l-1)
  v<-rep(0,s-1)
  shortA<-c(v,short)
  longA<-c(w,long)
  ex_means<-data.frame(shortA,longA)
  return(ex_means)
}



Histogram<-function(field,title)
{#This function gives distributions 
n_cl = floor(sqrt(length(field)))

p_cor<-seq(min(field),max(field),length=n_cl+1)

hist(field,breaks=p_cor,col="steelblue4",freq=FALSE, main=paste("Histogram of",title))
}


remove_outliers <- function(x) 
#This function omits outliers
#x=vector 
    {
    qnt <- quantile(x, probs=c(.25, .75))
    H <- 1.5 * IQR(x)
    y <- x
    y[x < (qnt[1] - H)] <- NA
    y[x > (qnt[2] + H)] <- NA
    return(y)
  }


BBollinger<-function(serie,s,confi)
#This functions gives Bands of Bollinger of a moving average.
#serie= data (We assume Normal distribution)
#s=period of time to apply moving average 
#confi=[0,1] level of confidence.
	{alpha<-(1-confi)/2
  
 	 rollmean<-rollapply(serie,s,mean)
  
 	 bbsup<-rollmean+abs(qnorm(alpha))*rollapply(serie,s,sd)
  
 	 bbinf<-rollmean-abs(qnorm(alpha))*rollapply(serie,s,sd)
  
#plot(c(0:max(bbsup)), col="white" , xlim=c(0,length(serie)) , ylab="commits", xlab="weeks", main="Bollinger Bands") 
#lines(bbsup,type="l",col="red")
#lines(rollmean,type="l",col="green")
#lines(bbinf,type="l",col="red")
#lines(serie, type="l", col="black", lty=2)
#legend("topleft",col=c("red","green","black"),lty=c(1,1,2),legend=c("Bollinger Bands","Rollmean","Commits"), bty="n", cex=0.8)
 	 end<-data.frame(rollmean,bbsup,bbinf)
	return(end)
	}





source('R/SCM.R')
source('R/MLS.R')
source('R/ITS.R')
