## Copyright (C) 2012, 2013 Bitergia
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details. 
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
##
## This file is a part of the vizGrimoire R package
##  (an R library for the MetricsGrimoire and vizGrimoire systems)
##
## Auxiliary.R
##
## Auxiliary code for the classes in the package
##
## Authors:
##   Jesus M. Gonzalez-Barahona <jgb@bitergia.com>
##   Daniel Izquierdo <dizquierdo@bitergia.com>
##   Alvaro del Castillo <acs@bitergia.com>
##
## Note: this file should be (alphabetically) the first one in the list
##  of files with R source code for the package. It seems that files are
##  run in alphabetic order, and this one includes facilities needed by
##  the rest. An alternative would be to use a "Collate" field in the
##  DESCRIPTION file.
##

## Get arguments from the command line
##
##  - dbschema: MySQL database schema to use, generated by CVSAnalY2
##  - user: MySQL user with permissions to access the schema
##  - passwd: password corresponding to user
##  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
##      (in fact, first day after the period)
##  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
##
##
ConfFromCommandLine <- function () {
  ## Get command line args, and produce variables for the script
  args <- commandArgs(trailingOnly = TRUE)

  if (length(args) > 3) {
    enddate <- args[4]
  } else {
    enddate <- "2100-01-01"
  }
  enddatesplit <- strsplit(enddate,'-')
  endyear <- enddatesplit[[1]][1]
  endmonth <- enddatesplit[[1]][2]
  enddate <- paste (c("'", enddate, "'"), collapse='')
  
  if (length(args) > 4) {
    startdate <- args[5]
  } else {
    startdate <- "1900-01-01"
  }
  startdatesplit <- strsplit(startdate,'-')
  startyear <- startdatesplit[[1]][1]
  startmonth <- startdatesplit[[1]][2]
  startdate <- paste (c("'", startdate, "'"), collapse='')

  conf <- list (database = args[1],
                user = args[2],
                password = args[3],
                startdate = startdate,
                enddate = enddate)
  return (conf)
}

library(optparse)

ConfFromOptParse <- function (datasource="") {
	option_list <- list(			
			make_option(c("-d", "--database"), dest="database", 
					help="Database with data"),
                        make_option(c("-i", "--identities"), dest="identities_db",
                                        help="Database with unique identities and affiliations"),
			make_option(c("-u", "--dbuser"), dest="dbuser", 
					help="Database user", default="root"),
			make_option(c("-p", "--dbpass"), dest="dbpassword", 
					help="Database user password", default=""),			
			make_option(c("-r", "--reports"), dest="reports", default="",
					help="Reports to be generated (repositories, companies)"),
			make_option(c("-s", "--start"), dest="startdate", 
					help="Start date for the report", default="1900-01-01"),
                        make_option(c("-g", "--granularity"), dest="granularity",
                                        help="Granularity for the report (months, weeks)", default="months"),
			make_option(c("-e", "--end"), dest="enddate", 
					help="End date for the report", default="2100-01-01")
	)	
	if (datasource == 'its') {
		option_list = c(option_list, make_option(
			c("-t", "--type"), dest="backend", 
			help="Type of backend: bugzilla, allura, jira, github", 
			default="bugzilla"));	
	}
	parser <- OptionParser(usage = "%prog [options]", option_list = option_list)
	options <- parse_args(parser)	
	if (is.null(options$database)) {		
		print_help(parser)
		stop("Database param is required")
	}
	enddatesplit <- strsplit(options$enddate,'-')
	endyear <- enddatesplit[[1]][1]
	endmonth <- enddatesplit[[1]][2]
        options$str_enddate <- options$enddate
	options$enddate <- paste (c("'", options$enddate, "'"), collapse='')
	
	startdatesplit <- strsplit(options$startdate,'-')
	startyear <- startdatesplit[[1]][1]
	startmonth <- startdatesplit[[1]][2]
        options$str_startdate <- options$startdate
	options$startdate <- paste (c("'", options$startdate, "'"), collapse='')

		
	return (options)
}

## Get arguments from parameters to this function
##
##  - dbschema: MySQL database schema to use, generated by CVSAnalY2
##  - user: MySQL user with permissions to access the schema
##  - passwd: password corresponding to user
##  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
##      (in fact, first day after the period)
##  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
##
##
ConfFromParameters <- function (dbschema, user = NULL, password = NULL,
                                host = "127.0.0.1", port = 3306,
                                group = NULL,
                                enddate = NULL, startdate = NULL) {
  if (is.null(enddate)) {
    enddate <- "2100-01-01"
  }
  enddate <- paste (c("'", enddate, "'"), collapse='')
  if (is.null(startdate)) {
    startdate <- "1900-01-01"
  }
  startdate <- paste (c("'", startdate, "'"), collapse='')

  conf <- list (database = dbschema,
                user = user,
                password = password,
                host = host,
                port = port,
                group = group,
                startdate = startdate,
                enddate = enddate)
  return (conf)
}

##
## Penalize scientific notation by 10 chars
##
options(scipen=10)

##
## Database-related classes & functions
##

library(RMySQL)
##
## Connect to the database and prepare...
##

SetDBChannel <- function (user=NULL, password=NULL, database,
                          host="127.0.0.1", port=3306,
                          group=NULL) {
  if (is.null(group)) {
    mychannel <<- dbConnect(MySQL(), user=user, password=password,
                            db=database, host=host, port=port)
  } else {
    mychannel <<- dbConnect(MySQL(), group=group,
                            db=database)
  }    
  dbGetQuery(mychannel, "SET NAMES 'utf8'")
}

##
## Close connection to the database
##

CloseDBChannel <- function () {
  dbDisconnect(mychannel)
}

##
## Find out kind of repository (bugzilla, launchpad, etc.) and
##  store it in common configuration list
##
FindoutRepoKind <- function () {
  q <- new ("Query", sql = "SELECT name FROM supported_trackers")
  kind <- run(q)$name[1]
  return (kind)
}

# Note use display.brewer.pal(...) to check colors
# example: display.brewer.pal(9, "Greens")
library(RColorBrewer)

blues = brewer.pal(5,'Blues')
reds = brewer.pal(5,'Reds')
greens = brewer.pal(5,'Greens')

#
# List of colors for plots
#
colors <- c("black", "green", "red", "blue", "orange", "brown")


# Complete a weekly dataframe with zero for missing weeks
#
# Gets as input a dataframe with weekly data. It hast to
# include a "yearweek" column, which is an integer year*52+week
# Produces a dataframe with zero rows for missing weeks
#
completeZeroWeekly <- function (data) {

  firstweek = as.integer(data$yearweek[1])
  lastweek = as.integer(data$yearweek[nrow(data)])
  weeks = data.frame('yearweek'=c(firstweek:lastweek))
  completedata <- merge (data, weeks, all=TRUE)
  completedata[is.na(completedata)] <- 0
  return (completedata)
}

# Merge two dataframes with weekly data, filling holes with 0
#
# Both dataframes should have a "yearweek" column,
# which is an integer year*52+week
#
mergeWeekly <- function (d1, d2) {

  d = completeZeroWeekly (merge (d1, d2, all=TRUE))

  return (d)
}

# Complete a monthly dataframe with zero for missing months
#
# Gets as input a dataframe with montly data. It hast to
# include a "id" column, which is an integer year*12+month
# Produces a dataframe with zero rows for missing months
#
completeZeroMonthly <- function (data) {

  #firstmonth = as.integer(data$id[1])
  firstmonth = 0
  lastmonth = as.integer(data$id[nrow(data)])
  months = data.frame('id'=c(firstmonth:lastmonth))
  completedata <- merge (data, months, all=TRUE)
  completedata[is.na(completedata)] <- 0
  return (completedata)
}

# Merge two dataframes with monthly data, filling holes with 0
#
# Both dataframes should have a "id" column,
# which is an integer year*12+week
#
mergeMonthly <- function (d1, d2) {

  d = completeZeroMonthly (merge (d1, d2, all=TRUE))

  return (d)
}

completeZeroPeriod <- function (data, nperiod, startdate, enddate){
    first = 0
    last = ceiling (difftime(as.POSIXlt(enddate), as.POSIXlt(startdate),units='days') / nperiod) - 1
    periods = data.frame('id'=c(first:last))
    completedata <- merge (data, periods, all=TRUE)
    completedata[is.na(completedata)] <- 0
    return (completedata)
}

##
## toTextDate: convert two vectors with integers for year, month into
##  a vector with text
##
## Example: 2012, 2 -> Feb 2012
##
toTextDate <- function (year, month) {
  abb.months <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
  text <- paste (abb.months[month], as.character(year))
  return (text)
}

##
## GetYear
##
## Get the year of a datetime object
##
## Year as four digits (eg: 2012)
##
GetYear <- function (time) {
  return (1900 + as.POSIXlt(time)$year)
}

##
## GetMonth
##
## Get the month of a datetime object
##
## Month as an integer 0:11 (eg: Jan is 0)
##
GetMonth <- function (time) {
  return (as.POSIXlt(time)$mon)
}

##
## GetWeek
##
## Get the week of a datetime object
##
## Week of the year as decimal number (00–53) as defined in ISO 8601. 
## If the week (starting on Monday) containing 1 January has four or 
## more days in the new year, then it is considered week 1. 
## Otherwise, it is the last week of the previous year, and the next week is week 1. 
## (Accepted but ignored on input.)
##
GetWeek  <- function (time) {
    return (format(time, "%V"))
}

## Group daily samples by selected period
completePeriod <- function (data, period, conf) {
        
    if (length(data) == 0) {
        # TODO: broken, only works for commit metric
        data <- data.frame(id=numeric(0), commits=numeric(0))
    }
    new_data <- completeZeroPeriod(data, period, conf$str_startdate, conf$str_enddate)
    new_data$week <- as.Date(conf$str_startdate) + new_data$id * period
    new_data$date  <- toTextDate(GetYear(new_data$week), GetMonth(new_data$week)+1)
    new_data[is.na(new_data)] <- 0
    new_data <- new_data[order(new_data$id), ]
        
    return (new_data)
}

GetPeriod <- function(period, date) {
    val = NULL
    
    if (!(period %in% c('weeks','months','years'))) 
        stop (paste("WRONG PERIOD", period))
    if (period == "weeks") val = GetWeek(date)
    else if (period == "months") val = GetMonth(date)
    else if (period == "years") val = GetYear(date)
    
    return (val)
}

GetDateText <- function(period, date) {
    val = NULL
    
    if (!(period %in% c('weeks','months','years'))) 
        stop (paste("WRONG PERIOD", period))
    if (period == "weeks") val = strftime(date, "%W %d %b %Y")
    # else if (period == "months") val = strftime(date, "%d %b %Y")
    else if (period == "months") val = strftime(date, "%b %Y")
    else if (period == "years") val = strftime(date, "%Y")
    
    return (val)
}

# Normalize JSON for all metrics
completePeriodMulti <- function(data, metrics, period,startdate, enddate) {    
    for (metric in metrics) {
        if (length(data[[metric]]) == 0) {
            metric_data <- data.frame(id=numeric(0), unknown=numeric(0))
        } else {
            metric_data <- data.frame(id=data$id,metric=data[[metric]])
        }
        colnames(metric_data)[2]<-metric      
        metric_data <- completePeriod2(metric_data, period, 
                conf$str_startdate, conf$str_enddate)
        if (!(exists('new_data'))) new_data <- metric_data
        else new_data <- merge(new_data, metric_data, all = TRUE)
    }
    return(new_data)    
}


## Group daily samples by selected period
completePeriod2 <- function (data, period, start, end, metric='unknow') {
    
    if (!(period %in% c('weeks','months','years'))) 
        stop (paste("WRONG PERIOD", period))   
    
    nperiod = 1 # sql resolution, days

    if (length(data) == 0) {
        data <- data.frame(id=numeric(0), unknown=numeric(0))
        colnames(data)[2]<-metric
    }
    
    for (column in names(data)) {
        if (column == "id") {next}
        else {metric = column; break}
    }
        
    new_data <- completeZeroPeriod(data, nperiod, start, end)
    new_data$week <- as.Date(start) + new_data$id * nperiod
    new_data$date  <- toTextDate(GetYear(new_data$week), GetMonth(new_data$week)+1)
    new_data[is.na(new_data)] <- 0
    new_data <- new_data[order(new_data$id), ]
    
    grouped_data <- list()
    
    cur_period = GetPeriod(period,as.Date(conf$str_startdate))
    cur_period_metric_val = 0
    count = 0
    for (i in 1:nrow(new_data)) {
        metric_val <- new_data[i,2]
        date <- new_data[i,3]
        date_period <- GetPeriod(period,date)
        
        if (date_period != cur_period) {
            # Store last period data
            grouped_data[['id']] <- c(grouped_data[['id']], past_date)
            grouped_data[[metric]] <- c(grouped_data[[metric]], 
                    cur_period_metric_val)
            grouped_data[['date']] <- c(grouped_data[['date']], 
                    GetDateText(period, past_date))                            
            grouped_data[['id2']] <- c(grouped_data[['id2']], count)
            count = count+1            
            cur_period_metric_val = metric_val
            cur_period = date_period
        } else {
            cur_period_metric_val = cur_period_metric_val + metric_val
            past_date = date
        }
    }
    if (date_period == cur_period) {
        grouped_data[['id']] <- c(grouped_data[['id']], date)
        grouped_data[[metric]] <- c(grouped_data[[metric]], cur_period_metric_val)        
        grouped_data[['date']] <- c(grouped_data[['date']], 
                GetDateText(period, date))
        grouped_data[['id2']] <- c(grouped_data[['id2']], count)
    }

    grouped_data<-data.frame(days=grouped_data[['id']],
            metric=grouped_data[[metric]],
            id=grouped_data[['id2']],
            date=grouped_data[['date']],stringsAsFactors=FALSE)
    colnames(grouped_data)[2]<-metric

    return (grouped_data)
}

#
# Plot several columns of a timeserie
#
#  data: data frame to plot
#  columns: names of the columns in data frame to plot
#  labels: strings to show as labels
#

## plotTimeSerieWeekN <- function (data, columns, filename, labels=columns) {

##   pdffilename <- paste (c(filename, ".pdf"), collapse='')
##   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
##   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')
  
##   # Build label for Y axis
##   label <- ""
##   for (col in 1:length(columns)) {
##     if (col != 1) {
##       label <- paste (c(label, " / "), collapse='')
##     }
##     label = paste (c(label, labels[col], " (", colors[col] ,")"),
##       collapse='')
##   }
  
##   # Regular plot
##   pdf(file=pdffilename, height=3.5, width=5)
##   timeserie <- ts (data[columns[1]],
##                    start=c(data$year[1],data$week[1]), frequency=52)
##   ts.plot (timeserie, col=colors[1], ylab=label)
##   if (length (columns) > 1) {
##     for (col in 2:length(columns)) {
##       timeserie <- ts (data[columns[col]],
##                        start=c(data$year[1],data$week[1]), frequency=52)
##       lines (timeserie, col=colors[col])
##     }
##   }
##   dev.off()

# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
## }

#
# Plot several columns of a timeserie
#
#  data: data frame to plot
#  columns: names of the columns in data frame to plot
#  labels: strings to show as labels
#

## plotTimeSerieMonthN <- function (data, columns, filename, labels=columns) {

##   pdffilename <- paste (c(filename, ".pdf"), collapse='')
##   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
##   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')
  
##   # Build label for Y axis
##   label <- ""
##   for (col in 1:length(columns)) {
##     if (col != 1) {
##       label <- paste (c(label, " / "), collapse='')
##     }
##     label = paste (c(label, labels[col], " (", colors[col] ,")"),
##       collapse='')
##   }
  
##   # Regular plot
##   pdf(file=pdffilename, height=3.5, width=5)
##   timeserie <- ts (data[columns[1]],
##                    start=c(data$year[1],data$month[1]), frequency=12)
##   ts.plot (timeserie, col=colors[1], ylab=label)
##   if (length (columns) > 1) {
##     for (col in 2:length(columns)) {
##       timeserie <- ts (data[columns[col]],
##                        start=c(data$year[1],data$month[1]), frequency=12)
##       lines (timeserie, col=colors[col])
##     }
##   }
##   dev.off()

# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
## }

## plotTimeSerieYearN <- function (data, columns, filename, labels=columns) {

##   pdffilename <- paste (c(filename, ".pdf"), collapse='')
##   pdffilenamelog <- paste (c(filename, "-log.pdf"), collapse='')
##   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
##   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')

##   # Build label for Y axis
##   label <- ""
##   for (col in 1:length(columns)) {
##     if (col != 1) {
##       label <- paste (c(label, " / "), collapse='')
##     }
##     label = paste (c(label, labels[col], " (", colors[col] ,")"),
##       collapse='')
##   }
  
##   timeserie <- ts (data[columns], start=data$year[1])
##   ## Regular plot
##   pdf(file=pdffilename, height=3.5, width=5)
##   ts.plot (timeserie, gpars=list(col=colors, ylab=label))
##   dev.off()
##   ## Log10 plot
##   pdf(file=pdffilenamelog, height=3.5, width=5)
##   ts.plot (log10(timeserie), gpars=list(col=colors, ylab=label))
##   dev.off()
  
  
# Cummulative plot
#    pdf(file=pdffilenamecum, height=3.5, width=5)
#    timeserie <- ts (cumsum(data[columns[1]]),
#       start=c(data$year[1],data$month[1]), frequency=12)
#    ts.plot (timeserie, col=colors[1], ylab=label)
#    if (length (columns) > 1) {
#       for (col in 2:length(columns)) {
#          timeserie <- ts (cumsum(data[columns[col]]),
#             start=c(data$year[1],data$month[1]), frequency=12)
#          lines (timeserie, col=colors[col])
#       }
#    }
#    dev.off()
## }


#
# Plot histogram and density of probability for data frame (single column)
#
plotHistogramTime <- function (data, filename, label, title='') {

  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdf(pdffilename, height=5, width=5)
#  hist(data, prob= T, breaks='FD', col=blues[3], xlab = label, main = title)
  hist(data, freq=TRUE, breaks=15, col="orange", xlab = label, main = title)
#  lines(density(data), col=reds[3], lwd = 2)
  dev.off()
}
#library(vioplot)

#
# Plot boxplot for data frame
#
plotBoxPlot <- function (data, filename, label = '', title = '') {
  
  pdffilename <- paste (c(filename, ".pdf"), collapse='')
  pdf(pdffilename, height=10, width=2)
  boxplot(data, col = greens[2], main = title, ylab = "days", xlab = label)
  # Mark top 3 outliers
  #top3 = rev(sort(data))[1:3]
  #print(top3)
  #text(rep(1,3), y = top3, label = paste(top3, 'days'), pos = 4)
  dev.off()
}

#
# Plot distribution of times
#
# Plots several charts:
#  - Histogram and density of probability for all tickets
#  - Histogram and density of probability for quickly closed tickets
#  - Histogram and density of probability for slowly closed tickets
# Threshold is for splitting in quick/slow (in days)
#
## plotTimeDist <- function (data, filename, unit = 'days', threshold = 30,
##                           variable = 'Time') {

##   label <- paste (c(variable, ' (', unit, ')'), collapse='')
##   # All tickets
##   plotHistogramTime (data, filename, label)
##   plotBoxPlot (data, paste (c (filename, '-boxplot'), collapse=''))
##   # Quickly closed tickets
##   quickly <- data[data <= threshold]
##   if (length(quickly) > 0) {
##     plotHistogramTime (quickly, paste (c (filename, '-quick'), collapse=''),
##                        label)
##     plotBoxPlot (quickly, paste (c (filename, '-quick-boxplot'), collapse=''))
##   }
##   # Slowly closed tickets
##   slowly <- data[data > threshold]
##   if (length(slowly) > 0) {
##     plotHistogramTime (slowly, paste (c (filename, '-slow'), collapse=''),
##                        label)
##     plotBoxPlot (slowly, paste (c (filename, '-slow-boxplot'), collapse=''))
##   }
## #  pdf(paste (c (filename, '-vioplot.pdf'), collapse=''), height=10, width=4)
## #  vioplot(data, quickly, slowly, col='gold', varwidth=TRUE)
## #  dev.off()
## }

## #
## # Plot time distributions and boxplots for time to fix in all years
## #
## plotTimeDistYear <- function (data, filename) {
##   for (year in data$year_open[1] : data$year_open[nrow(data)]) {
##     filename = paste(c(filename, '-',year), collapse='')
##     yearData <- data[data$year_open == year,]
##     plotTimeDist (yearData$ttofixm, filename, 'minutes',
##                   variable = 'Time to fix, first close')
##   }
## }

##
## Produce charts in several formats
##
produce.charts <- function (chart, filename, height = 4, width = 4) {
  if (! is.null(filename)) {
    pdffilename <- paste (c(filename, ".pdf"), collapse='')
    pdf(file=pdffilename, height=height, width=width)
    print (chart)
    dev.off()
    jpegfilename <- paste (c(filename, ".jpeg"), collapse='')
    jpeg(file=jpegfilename, height=height*75, width=width*75, quality=90)
    print (chart)
    dev.off()
  } else {
    print (chart)
  }
}

##
## binplot.3d
##
## Plot a bin in 3D, using rgl
## Code extracted from the rgl 3D histogram demo
##
binplot.3d <- function(x,y,z,alpha=1,topcol="red",sidecol="#aaaaaa")
{
  save <- par3d(skipRedraw=TRUE)
  on.exit(par3d(save))
  
  x1<-c(rep(c(x[1],x[2],x[2],x[1]),3),rep(x[1],4),rep(x[2],4))
  z1<-c(rep(0,4),rep(c(0,0,z,z),4))
  y1<-c(y[1],y[1],y[2],y[2],rep(y[1],4),rep(y[2],4),rep(c(y[1],y[2],y[2],y[1]),2))
  x2<-c(rep(c(x[1],x[1],x[2],x[2]),2),rep(c(x[1],x[2],rep(x[1],3),rep(x[2],3)),2))
  z2<-c(rep(c(0,z),4),rep(0,8),rep(z,8) )
  y2<-c(rep(y[1],4),rep(y[2],4),rep(c(rep(y[1],3),rep(y[2],3),y[1],y[2]),2) )
  rgl.quads(x1,z1,y1,col=rep(sidecol,each=4),alpha=alpha)
  rgl.quads(c(x[1],x[2],x[2],x[1]),rep(z,4),c(y[1],y[1],y[2],y[2]),
            col=rep(topcol,each=4),alpha=1) 
  rgl.lines(x2,z2,y2,col="#000000")
}

##
## hist3d
##
## Plot a 3D histogram
## Code based in the rgl 3D histogram demo
##
hist3d<-function(x,y=NULL,x.nclass="auto",y.nclass="auto",alpha=1,
                 cols=c("green","red","blue"),y.scale=200, z.scale=5)
{
  if (!is.numeric(y)) {
    values.y <- sort(unique(y))
    subst <- 0
    for (value in values.y) {
      subst <- subst + 1
      y[y==value] <- subst * y.scale
    }
    if (y.nclass == "auto") {
      y.nclass <- length(values.y)
    }
  }
  xy <- xy.coords(x,y)
  x <- xy$x
  if (x.nclass == "auto") {
    x.nclass<-ceiling(sqrt(nclass.Sturges(x)))
    }
  y <- xy$y
  breaks.x <- seq(min(x)-1,max(x)+1, length=(x.nclass+1))
  breaks.y <- seq(min(y)-1,max(y)+1,length=(y.nclass+1))
  z<-matrix(0,(x.nclass),(y.nclass))
  save <- par3d(skipRedraw=TRUE)
  on.exit(par3d(save))
  for (i in 1:x.nclass) 
  {
    for (j in 1:y.nclass) 
    {
      z[i, j] <- sum(x < breaks.x[i+1] & y < breaks.y[j+1] & 
        x >= breaks.x[i] & y >= breaks.y[j])
      binplot.3d(c(breaks.x[i],breaks.x[i+1]),c(breaks.y[j],breaks.y[j+1]),
                 z.scale*z[i,j],alpha=alpha,topcol=cols[j],sidecol=cols[j])
    }
  }
}


##
## Generic JSON function for using it in hierarchies of objects that need it
##
setGeneric (
 name= "JSON",
 def=function(.Object,...){standardGeneric("JSON")}
 )

##
## Generic Plot function for using it in hierarchies of objects that need it
##
setGeneric (
  name= "Plot",
  def=function(.Object,...){standardGeneric("Plot")}
  )

##
## Generic PlotDist function for using it in hierarchies of objects that need it
##
setGeneric (
 name= "PlotDist",
 def=function(object,...){standardGeneric("PlotDist")}
 )

##
## Code for producing JSON files suitable for vizGrimoire.JS
##
## All of this should still be re-coded as classes, but is here
## now for convenience, as a first step to support vizGrimoire.JS
##
library(rjson)

##
## Create a JSON file with some R object
##
createJSON <- function (data, filename) {
   sink(filename)
   cat(toJSON(data))
   sink()
}

source('R/SCM.R')
source('R/MLS.R')
source('R/ITS.R')
